import React from "react";
import { FiArrowLeft, FiArrowRight, FiCalendar, FiMapPin, FiUsers, FiX, FiClock, FiFileText } from "react-icons/fi";
import StatusBadge from "../ui/StatusBadge";
import { AttentionBadge, getTripAttention } from "./TripAttention";
import ActionsCell from "../actions/ActionsCell";
import IconButton from "../ui/IconButton";

const Detail=({icon:Icon,label,children,wide=false})=><div className={`rounded-xl border border-slate-200 bg-white p-3.5 ${wide?"sm:col-span-2":""}`}><div className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-[.1em] text-slate-400"><Icon size={12}/>{label}</div><div className="mt-1.5 text-sm font-medium text-slate-800">{children}</div></div>;
export default function TripWorkPanel({trip,permissions,onClose,onView,onStatusChange,onWorkflowAction,onAssignBus,onConfirmAction,onEdit,onSoftDelete,onPassengers}){
 if(!trip)return null;const attention=getTripAttention(trip,permissions);const date=trip.date?new Date(trip.date).toLocaleDateString(undefined,{weekday:"short",year:"numeric",month:"short",day:"numeric"}):"Date not set";const note=trip.changeRequestNote||trip.change_request_note||trip.quotationChangeNote||trip.quotation_change_note||trip.latestChangeRequest?.note||null;
 return <><div className="fixed inset-0 z-[55] bg-slate-950/20 backdrop-blur-[1px]" onClick={onClose}/><aside className="fixed inset-y-0 right-0 z-[60] flex w-full max-w-[560px] flex-col border-l border-slate-200 bg-slate-50 shadow-2xl">
  <div className="flex h-16 shrink-0 items-center justify-between border-b border-slate-200 bg-white px-5"><div className="flex min-w-0 items-center gap-3"><button onClick={onClose} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100 lg:hidden"><FiArrowLeft/></button><div className="min-w-0"><div className="text-[10px] font-bold uppercase tracking-[.14em] text-slate-400">Work item</div><div className="truncate text-sm font-semibold text-slate-950">{trip.tripType||"Transport booking"}</div></div></div><IconButton icon={FiX} label="Close work item" onClick={onClose}/></div>
  <div className="flex-1 overflow-y-auto">
   <div className="border-b border-slate-200 bg-white px-5 py-5"><div className="flex flex-wrap items-center gap-2"><StatusBadge>{trip.cancelRequest?"Cancel Requested":trip.status}</StatusBadge><AttentionBadge attention={attention}/></div><h2 className="mt-3 text-2xl font-semibold tracking-tight text-slate-950">{trip.destination||trip.tripType||"Trip"}</h2><p className="mt-1 text-sm text-slate-500">{trip.tripType||"Single transport booking"}</p></div>
   <div className="space-y-5 p-5">
    <section><div className="mb-2 text-[10px] font-bold uppercase tracking-[.14em] text-slate-400">Trip summary</div><div className="grid gap-2 sm:grid-cols-2"><Detail icon={FiCalendar} label="Date">{date}</Detail><Detail icon={FiClock} label="Departure">{trip.departureTime||"Not set"}</Detail><Detail icon={FiUsers} label="Passengers">{trip.students??trip.passengerCount??"—"}</Detail><Detail icon={FiMapPin} label="Destination">{trip.destination||"Not set"}</Detail></div></section>
    <section className={`rounded-xl border p-4 shadow-sm ${attention.tone==="action"?"border-amber-200 bg-amber-50":"border-slate-200 bg-white"}`}><div className="text-[10px] font-bold uppercase tracking-[.14em] text-slate-500">Next step</div><div className="mt-1.5 text-base font-semibold text-slate-950">{attention.title}</div><p className="mt-1 text-sm leading-6 text-slate-600">{attention.detail}</p></section>
    {note&&<section className="rounded-xl border border-violet-200 bg-violet-50 p-4"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.14em] text-violet-600"><FiFileText/>Change request note</div><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-800">{note}</p></section>}
    <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="mb-3"><div className="text-[10px] font-bold uppercase tracking-[.14em] text-slate-400">Actions</div><p className="mt-1 text-xs text-slate-500">Only actions currently available to you are shown.</p></div><ActionsCell trip={trip} hideView onStatusChange={onStatusChange} onWorkflowAction={onWorkflowAction} onAssignBus={onAssignBus} onConfirmAction={onConfirmAction} onView={onView} onEdit={onEdit} onSoftDelete={onSoftDelete}/>{onPassengers&&<button onClick={()=>onPassengers(trip)} className="mt-3 text-sm font-semibold text-slate-600 hover:text-slate-950">Passenger record</button>}</section>
   </div>
  </div>
  <div className="shrink-0 border-t border-slate-200 bg-white px-5 py-3"><button onClick={()=>onView?.(trip)} className="flex w-full items-center justify-between rounded-lg px-3 py-2.5 text-sm font-semibold text-slate-800 transition hover:bg-slate-100"><span>Open full trip record</span><FiArrowRight/></button></div>
 </aside></>
}
