import React,{useMemo,useState}from"react";
import{toast}from"react-toastify";
import{FiCalendar,FiMapPin,FiPlus}from"react-icons/fi";
import{createRecurringBooking}from"../../services/tripSeriesService";
import Button from"../ui/Button";import FeedbackBanner from"../ui/FeedbackBanner";import{FormField,SelectInput,TextArea,TextInput}from"../ui/FormControls";import JourneyLegEditor,{makeJourneyLeg}from"./JourneyLegEditor";
const initial={tripType:"Academic Trip",students:"",staff:"",notes:"",startDate:"",endDate:"",boosterSeatsRequested:false,boosterSeatCount:""};
const iso=d=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return`${y}-${m}-${day}`};const datesBetween=(start,end)=>{if(!start||!end||end<start)return[];const out=[],cursor=new Date(`${start}T12:00:00`),last=new Date(`${end}T12:00:00`);while(cursor<=last&&out.length<370){out.push(iso(cursor));cursor.setDate(cursor.getDate()+1)}return out};const nice=v=>new Date(`${v}T12:00:00`).toLocaleDateString(undefined,{weekday:"short",day:"numeric",month:"short"});
export default function RecurringBookingForm({schoolId,onSuccess,onCancel}){
const[form,setForm]=useState(initial),[excluded,setExcluded]=useState([]),[journeyLegs,setJourneyLegs]=useState(()=>[makeJourneyLeg(1,{origin:"School"})]),[submitting,setSubmitting]=useState(false),[error,setError]=useState("");
const set=(k,v)=>setForm(s=>({...s,[k]:v}));
const allDates=useMemo(()=>datesBetween(form.startDate,form.endDate),[form.startDate,form.endDate]);
const serviceDates=useMemo(()=>allDates.filter(d=>!excluded.includes(d)),[allDates,excluded]);
const toggleDate=d=>setExcluded(v=>v.includes(d)?v.filter(x=>x!==d):[...v,d]);
const updateLeg=(index,next)=>setJourneyLegs(v=>v.map((leg,i)=>i===index?next:leg));
const removeLeg=index=>setJourneyLegs(v=>v.filter((_,i)=>i!==index).map((leg,i)=>({...leg,sequence:i+1})));
const moveLeg=(index,direction)=>setJourneyLegs(v=>{const to=index+direction;if(to<0||to>=v.length)return v;const next=[...v];[next[index],next[to]]=[next[to],next[index]];return next.map((leg,i)=>({...leg,sequence:i+1}))});
const addLeg=()=>setJourneyLegs(v=>[...v,makeJourneyLeg(v.length+1)]);
const addReturn=()=>setJourneyLegs(v=>{const first=v[0]||{};return[...v,makeJourneyLeg(v.length+1,{label:"Return journey",origin:first.destination||"",destination:first.origin||"",departureTime:"03:30 PM"})]});
const submit=async e=>{e.preventDefault();setError("");if(!schoolId)return setError("Select a school workspace before creating a recurring booking.");if(!form.startDate||!form.endDate||form.endDate<form.startDate)return setError("Choose a valid service period.");if(!serviceDates.length)return setError("The service period must contain at least one active trip date.");if(!journeyLegs.length||journeyLegs.some(l=>!l.origin.trim()||!l.destination.trim()))return setError("Each journey needs a From and To location.");setSubmitting(true);try{const first=journeyLegs[0];const payload={...form,origin:first.origin,destination:first.destination,departureTime:first.departureTime,returnTime:journeyLegs[1]?.departureTime||null,recurrenceType:"daily",interval:1,daysOfWeek:[],occurrenceDates:allDates,excludedDates:excluded,journeyLegs:journeyLegs.map(({id,...leg})=>({...leg,stops:leg.stops.map(({id,...stop})=>stop)})),students:form.students===""?null:Number(form.students),staff:form.staff===""?null:Number(form.staff),boosterSeatCount:form.boosterSeatsRequested?Number(form.boosterSeatCount)||0:0};const result=await createRecurringBooking(schoolId,payload);toast.success(`${result?.occurrenceCount||serviceDates.length} trips created from recurring booking.`);onSuccess?.(result)}catch(err){const message=err?.response?.data?.message||"Recurring booking could not be created.";setError(message);toast.error(message)}finally{setSubmitting(false)}};
return <form onSubmit={submit}><div className="space-y-6 px-6 py-5">{error&&<FeedbackBanner tone="error" title="Recurring booking not created">{error}</FeedbackBanner>}
<section className="space-y-4"><div><h3 className="text-sm font-semibold text-slate-950">Default journeys</h3><p className="mt-0.5 text-xs text-slate-500">Define the transport movements that happen on each active date. Each dated trip inherits these journeys and stops.</p></div><FormField label="Trip type"><SelectInput value={form.tripType} onChange={e=>set("tripType",e.target.value)}><option>Academic Trip</option><option>Boarding House Trip</option><option>Day Trip</option><option>Sports Trip</option><option>Other</option></SelectInput></FormField>
<div className="space-y-4">{journeyLegs.map((leg,i)=><JourneyLegEditor key={leg.id} leg={leg} index={i} total={journeyLegs.length} onChange={next=>updateLeg(i,next)} onRemove={()=>removeLeg(i)} onMove={moveLeg}/>)}</div>
<div className="flex flex-wrap gap-2">{journeyLegs.length===1&&<Button type="button" variant="secondary" onClick={addReturn}><FiPlus/>Add return journey</Button>}<Button type="button" variant="secondary" onClick={addLeg}><FiPlus/>Add another journey</Button></div></section>
<section className="space-y-4 border-t border-slate-100 pt-5"><div><h3 className="text-sm font-semibold text-slate-950">Service period</h3><p className="mt-0.5 text-xs text-slate-500">Choose the actual period of transport, then remove any specific date that does not require a trip.</p></div><div className="grid gap-4 sm:grid-cols-2"><FormField label="From date"><TextInput type="date" value={form.startDate} onChange={e=>{set("startDate",e.target.value);setExcluded([])}} required/></FormField><FormField label="To date"><TextInput type="date" value={form.endDate} min={form.startDate||undefined} onChange={e=>{set("endDate",e.target.value);setExcluded([])}} required/></FormField></div>{allDates.length>0&&<div className="rounded-xl border border-slate-200 p-4"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><div className="flex items-center gap-2 text-sm font-semibold text-slate-900"><FiCalendar/>Trip dates</div><div className="mt-1 text-xs text-slate-500">Click a specific date to exclude or restore it.</div></div><div className="text-xs font-semibold text-slate-600">{serviceDates.length} active · {excluded.length} excluded</div></div><div className="flex flex-wrap gap-2">{allDates.map(d=>{const off=excluded.includes(d);return <button type="button" key={d} onClick={()=>toggleDate(d)} className={`rounded-lg border px-3 py-2 text-xs font-semibold transition ${off?"border-slate-200 bg-slate-50 text-slate-400 line-through":"border-indigo-200 bg-indigo-50 text-indigo-700 hover:border-indigo-300"}`}>{nice(d)}</button>})}</div></div>}<div className="rounded-xl border border-indigo-100 bg-indigo-50/50 px-4 py-3 text-sm text-slate-700"><span className="font-semibold text-slate-950">{serviceDates.length} trip{serviceDates.length===1?"":"s"}</span>{form.startDate&&form.endDate?` from ${nice(form.startDate)} to ${nice(form.endDate)}`:""}{excluded.length?` · ${excluded.length} date${excluded.length===1?"":"s"} excluded`:""}<div className="mt-1 text-xs text-slate-500"><FiMapPin className="mr-1 inline"/>{journeyLegs.length} journey{journeyLegs.length===1?"":"s"} per active date</div></div></section>
<section className="space-y-4 border-t border-slate-100 pt-5"><div><h3 className="text-sm font-semibold text-slate-950">Passengers</h3><p className="mt-0.5 text-xs text-slate-500">Default counts can later be adjusted on individual occurrences.</p></div><div className="grid gap-4 sm:grid-cols-2"><FormField label="Students" optional><TextInput type="number" min="0" value={form.students} onChange={e=>set("students",e.target.value)}/></FormField><FormField label="Staff" optional><TextInput type="number" min="0" value={form.staff} onChange={e=>set("staff",e.target.value)}/></FormField></div><label className="flex items-start gap-3 rounded-xl border border-slate-200 p-4"><input type="checkbox" checked={form.boosterSeatsRequested} onChange={e=>set("boosterSeatsRequested",e.target.checked)} className="mt-0.5 h-4 w-4 rounded border-slate-300"/><span><span className="block text-sm font-semibold text-slate-800">Booster seats required</span><span className="block text-xs text-slate-500">Apply this requirement to generated trips by default.</span></span></label>{form.boosterSeatsRequested&&<FormField label="Booster seats"><TextInput type="number" min="1" value={form.boosterSeatCount} onChange={e=>set("boosterSeatCount",e.target.value)} required/></FormField>}</section>
<section className="border-t border-slate-100 pt-5"><FormField label="Booking notes" optional><TextArea rows="4" value={form.notes} onChange={e=>set("notes",e.target.value)}/></FormField></section></div><div className="flex justify-end gap-2 border-t border-slate-100 bg-slate-50 px-6 py-4"><Button type="button" variant="secondary" onClick={onCancel} disabled={submitting}>Cancel</Button><Button type="submit" loading={submitting}>Create recurring booking</Button></div></form>
}