import React,{useCallback,useEffect,useState}from"react";
import{ToastContainer,toast}from"react-toastify";import"react-toastify/dist/ReactToastify.css";import dayjs from"dayjs";
import{listBookings,updateBooking}from"../services/bookingService";import{useAuth}from"../context/AuthContext";import BusBookingForm from"../components/booking/BusBookingForm";import ModalWrapper from"../components/ModalWrapper";
const EmptyRow=({children})=><div className="px-4 py-10 text-sm text-gray-500 text-center">{children}</div>;
function BookingModal({open,onClose,onSave,schoolId}){if(!open)return null;return <ModalWrapper title="New Bus Booking" onClose={onClose} maxWidth="max-w-3xl"><BusBookingForm schoolId={schoolId} onSuccess={async()=>{if(onSave)await onSave();onClose();}} onCancel={onClose}/></ModalWrapper>}
export default function Bookings(){const{activeWorkspace}=useAuth();const schoolId=activeWorkspace?.schoolId;const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false);
const load=useCallback(async()=>{if(!schoolId){setRows([]);setLoading(false);return;}try{setLoading(true);const data=await listBookings(schoolId);setRows(Array.isArray(data)?data:[]);}catch(e){console.error(e);toast.error("Could not load bookings.");setRows([]);}finally{setLoading(false);}},[schoolId]);useEffect(()=>{load();},[load]);
const setStatus=async(id,status)=>{await updateBooking(schoolId,id,{status});toast.success(`Marked ${status}.`);await load();};
if(!activeWorkspace)return <div className="p-6 text-sm text-gray-600">No school workspace is available for this account.</div>;
return <div className="space-y-4"><ToastContainer position="top-center" autoClose={1800} hideProgressBar/><header className="mb-2"><div className="mt-1 flex items-center justify-between"><h1 className="text-2xl font-semibold tracking-tight">Bus Bookings</h1><button className="px-3 py-2 rounded bg-violet-600 text-white hover:bg-violet-700" onClick={()=>setOpen(true)}>+ New Booking</button></div><p className="text-sm text-gray-600 mt-1">Create and manage ad-hoc bus bookings for {activeWorkspace.displayName||"this school"}.</p></header><div className="bg-white rounded shadow border border-gray-100"><div className="grid grid-cols-7 px-4 py-2 text-sm font-medium bg-gray-50"><div>Title</div><div>When</div><div>Students</div><div>Adults</div><div>Status</div><div>Created</div><div>Action</div></div>{loading?<EmptyRow>Loading...</EmptyRow>:rows.length===0?<EmptyRow>No bookings yet.</EmptyRow>:rows.map(r=><div key={r.id} className="grid grid-cols-7 px-4 py-2 border-t text-sm items-center"><div className="truncate">{r.title}</div><div>{r.date?dayjs(r.date).format("MMM D"):"—"} {r.startTime||""} → {r.endDate?dayjs(r.endDate).format("MMM D"):""} {r.endTime||""}</div><div>{r.students}</div><div>{r.adults}</div><div className="capitalize">{r.status}</div><div>{dayjs(r.createdAt).format("MMM D, YYYY")}</div><div className="flex gap-2">{r.status!=="approved"&&<button className="px-2 py-1 rounded border border-gray-300 hover:bg-gray-50 text-xs" onClick={()=>setStatus(r.id,"approved")}>Approve</button>}{r.status!=="cancelled"&&<button className="px-2 py-1 rounded bg-rose-600 text-white hover:bg-rose-700 text-xs" onClick={()=>setStatus(r.id,"cancelled")}>Cancel</button>}</div></div>)}</div><BookingModal open={open} onClose={()=>setOpen(false)} onSave={load} schoolId={schoolId}/></div>}
