import React,{useEffect,useState}from"react";
import{Navigate,useNavigate}from"react-router-dom";
import api from"../services/apiClient";
import{useAuth}from"../context/AuthContext";

export default function PlatformBootstrap(){
 const{profile,refreshSession}=useAuth(),navigate=useNavigate();
 const[status,setStatus]=useState(null),[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[confirmPassword,setConfirmPassword]=useState(""),[setupKey,setSetupKey]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{let active=true;api.get("/bootstrap/status").then(r=>active&&setStatus(r.data)).catch(()=>active&&setStatus({available:false,configured:false,completed:false}));return()=>{active=false}},[]);
 if(profile)return <Navigate to="/admin/platform" replace/>;
 async function submit(e){e.preventDefault();setError("");if(password!==confirmPassword){setError("Passwords do not match");return}setBusy(true);try{const{data}=await api.post("/bootstrap/platform-admin",{name,email,password,setupKey});if(data?.token)localStorage.setItem("token",data.token);await refreshSession();navigate("/admin/platform",{replace:true});}catch(err){setError(err?.response?.data?.message||"Platform setup failed");}finally{setBusy(false)}}
 if(!status)return <div className="min-h-screen flex items-center justify-center bg-gray-100">Checking platform setup…</div>;
 if(status.completed)return <div className="min-h-screen flex items-center justify-center bg-gray-100 p-4"><div className="bg-white rounded-xl shadow p-8 max-w-lg w-full"><h1 className="text-2xl font-semibold mb-3">Platform setup complete</h1><p className="text-gray-600 mb-6">The first Platform Super Admin already exists. Further administrators must be added from the Platform Control Center.</p><button onClick={()=>navigate("/login")} className="w-full bg-blue-600 text-white py-3 rounded-lg">Go to login</button></div></div>;
 if(!status.configured)return <div className="min-h-screen flex items-center justify-center bg-gray-100 p-4"><div className="bg-white rounded-xl shadow p-8 max-w-xl w-full"><h1 className="text-2xl font-semibold mb-3">Platform setup is locked</h1><p className="text-gray-600">Configure <code>PLATFORM_BOOTSTRAP_TOKEN</code> on the backend before creating the first Platform Super Admin. Optionally set <code>PLATFORM_BOOTSTRAP_EMAIL</code> to restrict setup to one email address.</p></div></div>;
 return <div className="min-h-screen flex items-center justify-center bg-gray-100 p-4"><form onSubmit={submit} className="bg-white rounded-xl shadow-lg p-8 w-full max-w-lg space-y-4"><div><div className="text-xs font-semibold tracking-wider text-blue-600 uppercase mb-2">One-time platform setup</div><h1 className="text-3xl font-semibold">Create Platform Super Admin</h1><p className="text-gray-600 mt-2">This creates the first canonical administrator with PLATFORM scope. This setup closes automatically after successful creation.</p></div>{error&&<div className="text-red-600 text-sm">{error}</div>}<label className="block"><span className="text-sm font-medium">Full name</span><input className="mt-1 w-full p-3 border rounded-lg" value={name} onChange={e=>setName(e.target.value)} required autoComplete="name"/></label><label className="block"><span className="text-sm font-medium">Email</span><input type="email" className="mt-1 w-full p-3 border rounded-lg" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/></label><label className="block"><span className="text-sm font-medium">Password</span><input type="password" minLength={10} className="mt-1 w-full p-3 border rounded-lg" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="new-password"/><span className="text-xs text-gray-500">Minimum 10 characters.</span></label><label className="block"><span className="text-sm font-medium">Confirm password</span><input type="password" minLength={10} className="mt-1 w-full p-3 border rounded-lg" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} required autoComplete="new-password"/></label><label className="block"><span className="text-sm font-medium">Platform setup key</span><input type="password" className="mt-1 w-full p-3 border rounded-lg" value={setupKey} onChange={e=>setSetupKey(e.target.value)} required autoComplete="off"/><span className="text-xs text-gray-500">Use the one-time setup key configured on the backend.</span></label><button disabled={busy} className="w-full bg-blue-600 text-white py-3 rounded-lg font-medium disabled:opacity-60">{busy?"Creating administrator…":"Create Platform Super Admin"}</button></form></div>;
}
