// Canonical operational datasource administration API.
import { Router } from "express";
import { prismaControl } from "../lib/prismaControl.js";
import { requireAuth } from "../middleware/auth.js";
import { requireCanonicalPermission } from "../middleware/canonicalAccess.js";
import { PERMISSIONS } from "../services/accessCatalog.js";
import { evictOperationalClient, getOperationalContextForOrganization } from "../services/operationalPrismaFactory.js";
const router=Router();router.use(requireAuth,requireCanonicalPermission(PERMISSIONS.ACCESS_ADMIN));
function clean(value,max=200,field="value"){const result=String(value??"").trim();if(!result)return null;if(result.length>max){const error=new Error(`${field} must be ${max} characters or fewer`);error.status=400;throw error;}return result;}
function parseMode(value){const result=String(value||"HOSTED").toUpperCase();if(!["HOSTED","CUSTOMER_POSTGRES"].includes(result)){const error=new Error("Unsupported data-source mode");error.status=400;throw error;}return result;}
const includeCredential={credential:{include:{secretProvider:true}}};
function view(row){return{id:row.id,organizationId:row.organizationId,name:row.name,mode:row.mode,engine:row.engine,providerLabel:row.providerLabel||null,region:row.region||null,isActive:row.isActive,schemaVersion:row.schemaVersion||null,lastVerifiedAt:row.lastVerifiedAt||null,updatedAt:row.updatedAt,credentialConfigured:Boolean(row.credential),secretProvider:row.credential?.secretProvider?{id:row.credential.secretProvider.id,key:row.credential.secretProvider.key,displayName:row.credential.secretProvider.displayName,type:row.credential.secretProvider.type}:null};}
router.get("/",async(req,res,next)=>{try{const organizationId=clean(req.query.organization_id,100,"organization_id"),tenantId=clean(req.query.tenant_id,100,"tenant_id");const where=organizationId?{organizationId}:tenantId?{organization:{tenantCoverage:{some:{tenantId}}}}:{};const rows=await prismaControl.operationalDataSource.findMany({where,include:includeCredential,orderBy:{updatedAt:"desc"}});return res.json(rows.map(view));}catch(error){return next(error);}});
router.put("/:schoolId",async(req,res,next)=>{try{const schoolId=clean(req.params.schoolId,100,"schoolId"),school=await prismaControl.organization.findUnique({where:{id:schoolId}});if(!school)return res.status(404).json({message:"School not found"});if(school.type!=="SCHOOL")return res.status(400).json({message:"Operational data sources can only be assigned to schools"});const requestedMode=parseMode(req.body?.mode),providerLabel=clean(req.body?.provider_label??req.body?.provider,100,"provider_label")||"postgresql",name=clean(req.body?.name,200,"name")||`${school.displayName} operational database`,region=clean(req.body?.region,100,"region"),activate=req.body?.is_active===undefined?true:Boolean(req.body.is_active),secretReference=clean(req.body?.secret_reference??req.body?.secret_ref,250,"secret_reference"),secretProviderId=clean(req.body?.secret_provider_id,100,"secret_provider_id"),secretProviderKey=clean(req.body?.secret_provider_key,100,"secret_provider_key")||"host-environment";let secretProvider=null;if(secretReference){secretProvider=secretProviderId?await prismaControl.secretProvider.findUnique({where:{id:secretProviderId}}):await prismaControl.secretProvider.findUnique({where:{key:secretProviderKey}});if(!secretProvider||!secretProvider.isActive)return res.status(400).json({message:"An active secret provider is required"});}const existing=await prismaControl.operationalDataSource.findFirst({where:{organizationId:schoolId,mode:requestedMode},include:includeCredential});if(!existing&&!secretReference)return res.status(400).json({message:"secret_reference is required when creating a data source"});const row=await prismaControl.$transaction(async tx=>{if(activate)await tx.operationalDataSource.updateMany({where:{organizationId:schoolId,isActive:true,...(existing?{id:{not:existing.id}}:{})},data:{isActive:false}});const dataSource=existing?await tx.operationalDataSource.update({where:{id:existing.id},data:{name,providerLabel,region,isActive:activate}}):await tx.operationalDataSource.create({data:{organizationId:schoolId,name,mode:requestedMode,engine:"postgresql",providerLabel,region,isActive:activate}});if(secretReference)await tx.dataSourceCredential.upsert({where:{dataSourceId:dataSource.id},create:{dataSourceId:dataSource.id,secretProviderId:secretProvider.id,secretReference,isActive:true},update:{secretProviderId:secretProvider.id,secretReference,isActive:true}});return tx.operationalDataSource.findUnique({where:{id:dataSource.id},include:includeCredential});});if(existing)await evictOperationalClient(existing.id);return res.status(existing?200:201).json(view(row));}catch(error){if(error?.code==="P2002")return res.status(409).json({message:"A conflicting data source already exists"});return next(error);}});
router.patch("/:id/status",async(req,res,next)=>{try{const id=clean(req.params.id,100,"data source id"),existing=await prismaControl.operationalDataSource.findUnique({where:{id}});if(!existing)return res.status(404).json({message:"Data source not found"});if(typeof req.body?.is_active!=="boolean")return res.status(400).json({message:"is_active must be boolean"});const row=await prismaControl.$transaction(async tx=>{if(req.body.is_active)await tx.operationalDataSource.updateMany({where:{organizationId:existing.organizationId,isActive:true,id:{not:id}},data:{isActive:false}});await tx.operationalDataSource.update({where:{id},data:{isActive:req.body.is_active}});return tx.operationalDataSource.findUnique({where:{id},include:includeCredential});});await evictOperationalClient(id);return res.json(view(row));}catch(error){return next(error);}});
router.post("/:id/verify",async(req,res,next)=>{try{const id=clean(req.params.id,100,"data source id"),existing=await prismaControl.operationalDataSource.findUnique({where:{id},include:includeCredential});if(!existing)return res.status(404).json({message:"Data source not found"});if(!existing.credential)return res.status(409).json({message:"This data source has no configured database credential",code:"DATA_SOURCE_SECRET_MISSING"});try{await evictOperationalClient(id);const{prisma}=await getOperationalContextForOrganization(existing.organizationId);await prisma.$queryRaw`SELECT 1`;}catch(error){console.error("Operational data-source verification failed",{dataSourceId:id,organizationId:existing.organizationId,provider:existing.providerLabel||null,errorCode:error?.code||null});return res.status(422).json({ok:false,code:"DATA_SOURCE_VERIFICATION_FAILED",message:"The operational database connection could not be verified. Check the configured credential, database availability, and network/SSL settings."});}const updated=await prismaControl.operationalDataSource.update({where:{id},data:{lastVerifiedAt:new Date()},include:includeCredential});return res.json({ok:true,verifiedAt:updated.lastVerifiedAt,dataSource:view(updated)});}catch(error){return next(error);}});
export default router;
