import { Router } from "express";
import { prismaControl } from "../lib/prismaControl.js";
import { requireAuth, requireAdmin } from "../middleware/auth.js";
const router=Router();router.use(requireAuth,requireAdmin);
const tenantView=t=>({id:t.id,name:t.name,slug:t.slug,status:t.status,subscription_mode:t.subscriptionMode,plan_key:t.planKey,subscription_start:t.subscriptionStart,subscription_end:t.subscriptionEnd});
const orgView=o=>({id:o.id,type:o.type,display_name:o.displayName,full_name:o.fullName,abbreviation:o.abbreviation,status:o.status});
function scopes(req){const access=req.effectiveAccess||{},platform=(access.platformAccess?.roles||[]).includes("super_admin"),tenantIds=[...new Set((access.platformAccess?.tenantScopes||[]).filter(x=>x.role==="tenant_admin").map(x=>x.tenantId).filter(Boolean))];return{platform,tenantIds}}
router.get("/context",async(req,res,next)=>{try{const s=scopes(req);if(s.platform)return res.json({mode:"platform",tenant_scopes:[]});if(!s.tenantIds.length)return res.status(403).json({message:"No delegated administration scope"});const tenants=await prismaControl.tenant.findMany({where:{id:{in:s.tenantIds}},orderBy:{name:"asc"}});res.json({mode:"tenant",tenant_scopes:tenants.map(tenantView),default_tenant_id:tenants[0]?.id||null})}catch(e){next(e)}});
router.get("/tenants/:tenantId",async(req,res,next)=>{try{const s=scopes(req),tenantId=req.params.tenantId;if(!s.platform&&!s.tenantIds.includes(tenantId))return res.status(403).json({message:"This tenant is outside your administration scope"});const tenant=await prismaControl.tenant.findUnique({where:{id:tenantId}});if(!tenant)return res.status(404).json({message:"Tenant not found"});const coverage=await prismaControl.tenantOrganization.findMany({where:{tenantId},include:{organization:true},orderBy:{createdAt:"asc"}}),orgIds=coverage.map(x=>x.organizationId);const[memberships,assignments,relationships,sources]=await Promise.all([prismaControl.organizationMembership.findMany({where:{organizationId:{in:orgIds},status:"ACTIVE"},include:{user:true}}),prismaControl.roleAssignment.findMany({where:{isActive:true,OR:[{tenantId},{organizationId:{in:orgIds}}]},include:{user:true,role:true,organization:true}}),prismaControl.organizationRelationship.findMany({where:{status:"ACTIVE",OR:[{fromOrganizationId:{in:orgIds}},{toOrganizationId:{in:orgIds}}]},include:{fromOrganization:true,toOrganization:true}}),prismaControl.operationalDataSource.findMany({where:{organizationId:{in:orgIds}}})]);const users=new Map();memberships.forEach(x=>users.set(x.user.id,x.user));assignments.forEach(x=>users.set(x.user.id,x.user));res.json({tenant:tenantView(tenant),metrics:{organizations:orgIds.length,users:users.size,relationships:relationships.length,active_data_sources:sources.filter(x=>x.isActive).length},organizations:coverage.map(x=>({...orgView(x.organization),coverage_type:x.coverageType})),users:[...users.values()].map(u=>({id:u.id,email:u.email,display_name:u.displayName,status:u.status})),assignments:assignments.map(a=>({id:a.id,scope_type:a.scopeType,user:{id:a.user.id,email:a.user.email,display_name:a.user.displayName},role:{key:a.role.key,name:a.role.name},organization:a.organization?orgView(a.organization):null})),relationships:relationships.map(r=>({id:r.id,type:r.type,from:orgView(r.fromOrganization),to:orgView(r.toOrganization)})),data_sources:sources.map(x=>({id:x.id,name:x.name,organization_id:x.organizationId,mode:x.mode,provider_label:x.providerLabel||x.engine,is_active:x.isActive}))})}catch(e){next(e)}});
export default router;
