import { Router } from "express";
import { prismaControl } from "../lib/prismaControl.js";
import { requireAuth, requireAdmin } from "../middleware/auth.js";
import { PERMISSIONS } from "../services/accessCatalog.js";

const router=Router();router.use(requireAuth,requireAdmin);
const DELEGABLE=new Set([PERMISSIONS.TRIP_APPROVE_QUOTE]);
const clean=v=>String(v||"").trim();
async function actor(req){const id=clean(req.effectiveAccess?.user?.appUserId);if(!id){const e=new Error("Canonical administrator identity not found");e.status=403;throw e;}return id;}
async function canAdminOrganization(req,organizationId){const actorId=await actor(req);const assignment=await prismaControl.roleAssignment.findFirst({where:{userId:actorId,isActive:true,OR:[{scopeType:"PLATFORM",role:{key:"super_admin"}},{scopeType:"ORGANIZATION",organizationId,role:{key:{in:["tenant_admin","super_admin"]}}},{scopeType:"TENANT",tenant:{organizations:{some:{organizationId}}},role:{key:{in:["tenant_admin","super_admin"]}}}]}});if(!assignment){const e=new Error("Forbidden for this organization");e.status=403;throw e;}return actorId;}
const view=g=>({id:g.id,user_id:g.userId,organization_id:g.organizationId,permission:g.permission?.key,is_active:g.isActive});

router.get("/",async(req,res,next)=>{try{const organizationId=clean(req.query.organization_id);if(!organizationId)return res.status(400).json({message:"organization_id is required"});await canAdminOrganization(req,organizationId);const rows=await prismaControl.userPermissionGrant.findMany({where:{organizationId,isActive:true},include:{permission:true},orderBy:{createdAt:"asc"}});return res.json(rows.map(view));}catch(e){next(e);}});
router.get("/catalog",async(req,res)=>res.json([{key:PERMISSIONS.TRIP_APPROVE_QUOTE,name:"Approve trip quotations",description:"Can approve a bus operator quotation for trips in this organization."}]));
router.post("/",async(req,res,next)=>{try{const userId=clean(req.body?.user_id),organizationId=clean(req.body?.organization_id),permissionKey=clean(req.body?.permission);if(!userId||!organizationId||!permissionKey)return res.status(400).json({message:"user_id, organization_id and permission are required"});if(!DELEGABLE.has(permissionKey))return res.status(400).json({message:"This permission is not individually delegable"});const actorId=await canAdminOrganization(req,organizationId);const membership=await prismaControl.organizationMembership.findUnique({where:{userId_organizationId:{userId,organizationId}}});if(!membership||membership.status!=="ACTIVE")return res.status(400).json({message:"The user must be an active member of this organization"});const permission=await prismaControl.permission.findUnique({where:{key:permissionKey}});if(!permission)return res.status(404).json({message:"Permission is not configured"});const grant=await prismaControl.userPermissionGrant.upsert({where:{userId_permissionId_organizationId:{userId,permissionId:permission.id,organizationId}},update:{isActive:true},create:{userId,permissionId:permission.id,organizationId,isActive:true},include:{permission:true}});await prismaControl.auditEvent.create({data:{organizationId,actorUserId:actorId,action:"user.permission.granted",resourceType:"app_user",resourceId:userId,metadata:{permission:permissionKey}}});return res.status(201).json(view(grant));}catch(e){next(e);}});
router.delete("/:id",async(req,res,next)=>{try{const grant=await prismaControl.userPermissionGrant.findUnique({where:{id:clean(req.params.id)},include:{permission:true}});if(!grant)return res.status(404).json({message:"Permission grant not found"});const actorId=await canAdminOrganization(req,grant.organizationId);await prismaControl.userPermissionGrant.delete({where:{id:grant.id}});await prismaControl.auditEvent.create({data:{organizationId:grant.organizationId,actorUserId:actorId,action:"user.permission.revoked",resourceType:"app_user",resourceId:grant.userId,metadata:{permission:grant.permission?.key}}});return res.status(204).end();}catch(e){next(e);}});
export default router;
