import { Router } from "express";
import bcrypt from "bcryptjs";
import { prismaControl } from "../lib/prismaControl.js";
import { requireAuth, requireAdmin } from "../middleware/auth.js";
import { normalizeEmail, registerLocalUser } from "../services/canonicalAuth.js";

const router=Router();router.use(requireAuth,requireAdmin);
async function actor(req){const legacy=Number(req.user?.id);const user=await prismaControl.appUser.findFirst({where:{OR:[...(Number.isInteger(legacy)?[{legacyUserId:legacy}]:[]),...(req.user?.email?[{email:req.user.email}]:[])]}});if(!user)return null;const admin=await prismaControl.roleAssignment.findFirst({where:{userId:user.id,isActive:true,scopeType:"PLATFORM",role:{key:"super_admin"}}});return admin?user:null}
async function audit(user,{tenantId=null,organizationId=null,action,resourceType,resourceId,metadata={}}){await prismaControl.auditEvent.create({data:{actorUserId:user.id,tenantId,organizationId,action,resourceType,resourceId,metadata}})}
const orgView=o=>({id:o.id,type:o.type,display_name:o.displayName,full_name:o.fullName,abbreviation:o.abbreviation,status:o.status});

router.get("/organizations/:organizationId/options",async(req,res,next)=>{try{if(!(await actor(req)))return res.status(403).json({message:"Platform Super Admin access required"});const organization=await prismaControl.organization.findUnique({where:{id:req.params.organizationId}});if(!organization)return res.status(404).json({message:"Organization not found"});const[organizations,roles,users]=await Promise.all([prismaControl.organization.findMany({where:{id:{not:organization.id},status:"active"},orderBy:{displayName:"asc"}}),prismaControl.role.findMany({orderBy:{name:"asc"}}),prismaControl.appUser.findMany({orderBy:{displayName:"asc"}})]);res.json({organizations:organizations.map(orgView),roles:roles.map(r=>({id:r.id,key:r.key,name:r.name,description:r.description})),users:users.map(u=>({id:u.id,email:u.email,display_name:u.displayName,status:u.status}))})}catch(e){next(e)}});

router.post("/organizations/:organizationId/relationships",async(req,res,next)=>{try{const user=await actor(req);if(!user)return res.status(403).json({message:"Platform Super Admin access required"});const fromOrganizationId=req.params.organizationId,toOrganizationId=String(req.body?.toOrganizationId||""),type=String(req.body?.type||"").toUpperCase(),allowed=["BELONGS_TO_GROUP","TRANSPORT_PROVIDER","TRIP_MANAGER","WORKS_WITH_TRANSPORT_PROVIDER"];if(!toOrganizationId||fromOrganizationId===toOrganizationId)return res.status(400).json({message:"Select another organization"});if(!allowed.includes(type))return res.status(400).json({message:"Invalid relationship type"});const target=await prismaControl.organization.findUnique({where:{id:toOrganizationId}});if(!target)return res.status(404).json({message:"Target organization not found"});const relationship=await prismaControl.organizationRelationship.upsert({where:{fromOrganizationId_toOrganizationId_type:{fromOrganizationId,toOrganizationId,type}},update:{status:"active",isPrimary:Boolean(req.body?.isPrimary),notes:req.body?.notes||null},create:{fromOrganizationId,toOrganizationId,type,status:"active",isPrimary:Boolean(req.body?.isPrimary),notes:req.body?.notes||null}});await audit(user,{organizationId:fromOrganizationId,action:"relationship.created",resourceType:"organization_relationship",resourceId:relationship.id,metadata:{toOrganizationId,type}});res.status(201).json({id:relationship.id})}catch(e){next(e)}});

router.post("/organizations/:organizationId/users",async(req,res,next)=>{try{const user=await actor(req);if(!user)return res.status(403).json({message:"Platform Super Admin access required"});const organizationId=req.params.organizationId,email=normalizeEmail(req.body?.email),displayName=String(req.body?.displayName||"").trim(),roleKey=String(req.body?.roleKey||"").trim(),jobTitle=String(req.body?.jobTitle||"").trim()||null,password=String(req.body?.password||"");if(!email||!displayName||!roleKey)return res.status(400).json({message:"Name, email and role are required"});const organization=await prismaControl.organization.findUnique({where:{id:organizationId}}),role=await prismaControl.role.findUnique({where:{key:roleKey}});if(!organization||!role)return res.status(404).json({message:"Organization or role not found"});let appUser=await prismaControl.appUser.findUnique({where:{email}}),created=false;if(!appUser){if(password.length<10||password.length>128)return res.status(400).json({message:"A 10–128 character initial password is required for a new user"});appUser=await registerLocalUser({email,displayName,passwordHash:await bcrypt.hash(password,12)});created=true}else if(password)return res.status(400).json({message:"This email is already registered; leave initial password blank"});await prismaControl.appUser.update({where:{id:appUser.id},data:{status:"active",displayName:displayName||appUser.displayName}});await prismaControl.organizationMembership.upsert({where:{userId_organizationId:{userId:appUser.id,organizationId}},update:{status:"ACTIVE",jobTitle},create:{userId:appUser.id,organizationId,status:"ACTIVE",jobTitle}});const existing=await prismaControl.roleAssignment.findFirst({where:{userId:appUser.id,roleId:role.id,scopeType:"ORGANIZATION",organizationId}});if(existing)await prismaControl.roleAssignment.update({where:{id:existing.id},data:{isActive:true}});else await prismaControl.roleAssignment.create({data:{userId:appUser.id,roleId:role.id,scopeType:"ORGANIZATION",organizationId,isActive:true}});await audit(user,{organizationId,action:created?"user.onboarded":"user.organization_access_added",resourceType:"app_user",resourceId:appUser.id,metadata:{email,roleKey,jobTitle}});res.status(201).json({user:{id:appUser.id,email:appUser.email,display_name:appUser.displayName},created})}catch(e){if(e?.code==="P2002")return res.status(409).json({message:"That user or assignment already exists"});next(e)}});
export default router;
