// Workspace-routed passenger API. Passenger PII requires both dedicated
// passenger permission and authorization to read the parent Trip.
import { Router } from "express";
import { requireAuth } from "../middleware/auth.js";
import { PERMISSIONS } from "../services/accessCatalog.js";
import { operationalPrismaForWorkspace } from "../services/workspaceOperationalContext.js";
import { canManageWorkspacePassengers,canReadWorkspacePassengers } from "../services/workspaceAuthorization.js";
const router=Router({mergeParams:true});router.use(requireAuth);const MAX_PASSENGERS_PER_REQUEST=250;
const PASSENGER_SELECT={id:true,tripId:true,createdAt:true,fullName:true,guardianName:true,guardianPhone:true,pickupPoint:true,dropoffPoint:true,notes:true,checkedIn:true};
function positiveInt(v,f){const n=Number(v);if(!Number.isInteger(n)||n<=0){const e=new Error(`${f} must be a positive integer`);e.status=400;throw e;}return n;}
function cleanOptional(v,m){if(v===undefined||v===null||v==="")return null;const t=String(v).trim();if(!t)return null;if(t.length>m){const e=new Error(`Value exceeds maximum length of ${m}`);e.status=400;throw e;}return t;}
function cleanRequired(v,f,m){const t=String(v??"").trim();if(!t){const e=new Error(`${f} is required`);e.status=400;throw e;}if(t.length>m){const e=new Error(`${f} exceeds maximum length of ${m}`);e.status=400;throw e;}return t;}
function normalizePassenger(i){return{fullName:cleanRequired(i?.fullName,"fullName",200),guardianName:cleanOptional(i?.guardianName,200),guardianPhone:cleanOptional(i?.guardianPhone,100),pickupPoint:cleanOptional(i?.pickupPoint,500),dropoffPoint:cleanOptional(i?.dropoffPoint,500),notes:cleanOptional(i?.notes,2000),checkedIn:false};}
function passengerPatch(b={}){const a=new Set(["fullName","guardianName","guardianPhone","pickupPoint","dropoffPoint","notes","checkedIn"]),u=Object.keys(b).filter(k=>!a.has(k));if(u.length){const e=new Error(`Unsupported passenger fields: ${u.join(", ")}`);e.status=400;throw e;}const p={};if(b.fullName!==undefined)p.fullName=cleanRequired(b.fullName,"fullName",200);if(b.guardianName!==undefined)p.guardianName=cleanOptional(b.guardianName,200);if(b.guardianPhone!==undefined)p.guardianPhone=cleanOptional(b.guardianPhone,100);if(b.pickupPoint!==undefined)p.pickupPoint=cleanOptional(b.pickupPoint,500);if(b.dropoffPoint!==undefined)p.dropoffPoint=cleanOptional(b.dropoffPoint,500);if(b.notes!==undefined)p.notes=cleanOptional(b.notes,2000);if(b.checkedIn!==undefined){if(typeof b.checkedIn!=="boolean"){const e=new Error("checkedIn must be boolean");e.status=400;throw e;}p.checkedIn=b.checkedIn;}return p;}
async function loadSchoolTrip(prisma,schoolId,tripId){return prisma.trip.findFirst({where:{id:tripId,owningSchoolOrganizationId:schoolId},select:{id:true,createdByAppUserId:true,status:true}});}
async function contextAndTrip(req,p){const tripId=positiveInt(req.params.tripId,"trip id"),c=await operationalPrismaForWorkspace(req.user,req.params.schoolId,p),trip=await loadSchoolTrip(c.prisma,c.workspace.schoolId,tripId);return{...c,tripId,trip};}
router.get("/",async(req,res,next)=>{try{const{prisma,access,workspace,tripId,trip}=await contextAndTrip(req,PERMISSIONS.PASSENGER_READ);if(!trip)return res.status(404).json({message:"Trip not found"});if(!canReadWorkspacePassengers({access,workspace,trip}))return res.status(403).json({message:"Forbidden"});return res.json(await prisma.tripPassenger.findMany({where:{tripId},orderBy:[{fullName:"asc"},{id:"asc"}],select:PASSENGER_SELECT}));}catch(e){return next(e);}});
router.post("/",async(req,res,next)=>{try{const{prisma,access,workspace,tripId,trip}=await contextAndTrip(req,PERMISSIONS.PASSENGER_MANAGE);if(!trip)return res.status(404).json({message:"Trip not found"});if(!canManageWorkspacePassengers({access,workspace,trip}))return res.status(403).json({message:"Forbidden"});const list=req.body?.passengers;if(!Array.isArray(list)||!list.length)return res.status(400).json({message:"passengers must be a non-empty array"});if(list.length>MAX_PASSENGERS_PER_REQUEST)return res.status(400).json({message:`A maximum of ${MAX_PASSENGERS_PER_REQUEST} passengers may be added at once`});const passengers=list.map(normalizePassenger),created=await prisma.$transaction(passengers.map(passenger=>prisma.tripPassenger.create({data:{tripId,...passenger},select:PASSENGER_SELECT})));return res.status(201).json(created);}catch(e){return next(e);}});
router.patch("/:passengerId",async(req,res,next)=>{try{const passengerId=positiveInt(req.params.passengerId,"passenger id"),{prisma,access,workspace,tripId,trip}=await contextAndTrip(req,PERMISSIONS.PASSENGER_MANAGE);if(!trip)return res.status(404).json({message:"Trip not found"});if(!canManageWorkspacePassengers({access,workspace,trip}))return res.status(403).json({message:"Forbidden"});const p=passengerPatch(req.body||{});if(!Object.keys(p).length)return res.status(400).json({message:"No supported fields supplied"});const existing=await prisma.tripPassenger.findFirst({where:{id:passengerId,tripId},select:{id:true}});if(!existing)return res.status(404).json({message:"Passenger not found"});return res.json(await prisma.tripPassenger.update({where:{id:passengerId},data:p,select:PASSENGER_SELECT}));}catch(e){return next(e);}});
router.delete("/:passengerId",async(req,res,next)=>{try{const passengerId=positiveInt(req.params.passengerId,"passenger id"),{prisma,access,workspace,tripId,trip}=await contextAndTrip(req,PERMISSIONS.PASSENGER_MANAGE);if(!trip)return res.status(404).json({message:"Trip not found"});if(!canManageWorkspacePassengers({access,workspace,trip}))return res.status(403).json({message:"Forbidden"});const r=await prisma.tripPassenger.deleteMany({where:{id:passengerId,tripId}});if(!r.count)return res.status(404).json({message:"Passenger not found"});return res.status(204).end();}catch(e){return next(e);}});
export default router;
