// Workspace-routed passenger API.
// Passenger PII is behind dedicated workspace permissions and resource policy.

import { Router } from "express";
import { requireAuth } from "../middleware/auth.js";
import { PERMISSIONS } from "../services/accessCatalog.js";
import { operationalPrismaForWorkspace } from "../services/workspaceOperationalContext.js";
import { canManageWorkspacePassengers, canReadWorkspacePassengers } from "../services/workspaceAuthorization.js";

const router = Router({ mergeParams: true });
router.use(requireAuth);
const MAX_PASSENGERS_PER_REQUEST = 250;
const PASSENGER_SELECT = { id:true, tripId:true, createdAt:true, fullName:true, guardianName:true, guardianPhone:true, pickupPoint:true, dropoffPoint:true, notes:true, checkedIn:true };

function positiveInt(value, field) { const parsed=Number(value); if(!Number.isInteger(parsed)||parsed<=0){const e=new Error(`${field} must be a positive integer`);e.status=400;throw e;} return parsed; }
function cleanOptional(value,maxLength){if(value===undefined||value===null||value==="")return null;const text=String(value).trim();if(!text)return null;if(text.length>maxLength){const e=new Error(`Value exceeds maximum length of ${maxLength}`);e.status=400;throw e;}return text;}
function cleanRequired(value,field,maxLength){const text=String(value??"").trim();if(!text){const e=new Error(`${field} is required`);e.status=400;throw e;}if(text.length>maxLength){const e=new Error(`${field} exceeds maximum length of ${maxLength}`);e.status=400;throw e;}return text;}
function normalizePassenger(input){return{fullName:cleanRequired(input?.fullName,"fullName",200),guardianName:cleanOptional(input?.guardianName,200),guardianPhone:cleanOptional(input?.guardianPhone,100),pickupPoint:cleanOptional(input?.pickupPoint,500),dropoffPoint:cleanOptional(input?.dropoffPoint,500),notes:cleanOptional(input?.notes,2000),checkedIn:false};}
function passengerPatch(body={}){const allowed=new Set(["fullName","guardianName","guardianPhone","pickupPoint","dropoffPoint","notes","checkedIn"]);const unknown=Object.keys(body).filter(k=>!allowed.has(k));if(unknown.length){const e=new Error(`Unsupported passenger fields: ${unknown.join(", ")}`);e.status=400;throw e;}const p={};if(body.fullName!==undefined)p.fullName=cleanRequired(body.fullName,"fullName",200);if(body.guardianName!==undefined)p.guardianName=cleanOptional(body.guardianName,200);if(body.guardianPhone!==undefined)p.guardianPhone=cleanOptional(body.guardianPhone,100);if(body.pickupPoint!==undefined)p.pickupPoint=cleanOptional(body.pickupPoint,500);if(body.dropoffPoint!==undefined)p.dropoffPoint=cleanOptional(body.dropoffPoint,500);if(body.notes!==undefined)p.notes=cleanOptional(body.notes,2000);if(body.checkedIn!==undefined){if(typeof body.checkedIn!=="boolean"){const e=new Error("checkedIn must be boolean");e.status=400;throw e;}p.checkedIn=body.checkedIn;}return p;}
async function loadSchoolTrip(prisma,schoolId,tripId){return prisma.trip.findFirst({where:{id:tripId,owningSchoolOrganizationId:schoolId},select:{id:true,createdByAppUserId:true,status:true}});}
async function contextAndTrip(req,permission){const tripId=positiveInt(req.params.tripId,"trip id");const context=await operationalPrismaForWorkspace(req.user,req.params.schoolId,permission);const trip=await loadSchoolTrip(context.prisma,context.workspace.schoolId,tripId);return{...context,tripId,trip};}

router.get("/",async(req,res,next)=>{try{const{prisma,workspace,tripId,trip}=await contextAndTrip(req,PERMISSIONS.PASSENGER_READ);if(!trip)return res.status(404).json({message:"Trip not found"});if(!canReadWorkspacePassengers({workspace}))return res.status(403).json({message:"Forbidden"});const rows=await prisma.tripPassenger.findMany({where:{tripId},orderBy:[{fullName:"asc"},{id:"asc"}],select:PASSENGER_SELECT});return res.json(rows);}catch(e){return next(e);}});
router.post("/",async(req,res,next)=>{try{const{prisma,access,workspace,tripId,trip}=await contextAndTrip(req,PERMISSIONS.PASSENGER_MANAGE);if(!trip)return res.status(404).json({message:"Trip not found"});if(!canManageWorkspacePassengers({access,workspace,trip}))return res.status(403).json({message:"Forbidden"});const list=req.body?.passengers;if(!Array.isArray(list)||!list.length)return res.status(400).json({message:"passengers must be a non-empty array"});if(list.length>MAX_PASSENGERS_PER_REQUEST)return res.status(400).json({message:`A maximum of ${MAX_PASSENGERS_PER_REQUEST} passengers may be added at once`});const passengers=list.map(normalizePassenger);const created=await prisma.$transaction(passengers.map(passenger=>prisma.tripPassenger.create({data:{tripId,...passenger},select:PASSENGER_SELECT})));return res.status(201).json(created);}catch(e){return next(e);}});
router.patch("/:passengerId",async(req,res,next)=>{try{const passengerId=positiveInt(req.params.passengerId,"passenger id");const{prisma,access,workspace,tripId,trip}=await contextAndTrip(req,PERMISSIONS.PASSENGER_MANAGE);if(!trip)return res.status(404).json({message:"Trip not found"});if(!canManageWorkspacePassengers({access,workspace,trip}))return res.status(403).json({message:"Forbidden"});const p=passengerPatch(req.body||{});if(!Object.keys(p).length)return res.status(400).json({message:"No supported fields supplied"});const existing=await prisma.tripPassenger.findFirst({where:{id:passengerId,tripId},select:{id:true}});if(!existing)return res.status(404).json({message:"Passenger not found"});return res.json(await prisma.tripPassenger.update({where:{id:passengerId},data:p,select:PASSENGER_SELECT}));}catch(e){return next(e);}});
router.delete("/:passengerId",async(req,res,next)=>{try{const passengerId=positiveInt(req.params.passengerId,"passenger id");const{prisma,access,workspace,tripId,trip}=await contextAndTrip(req,PERMISSIONS.PASSENGER_MANAGE);if(!trip)return res.status(404).json({message:"Trip not found"});if(!canManageWorkspacePassengers({access,workspace,trip}))return res.status(403).json({message:"Forbidden"});const result=await prisma.tripPassenger.deleteMany({where:{id:passengerId,tripId}});if(!result.count)return res.status(404).json({message:"Passenger not found"});return res.status(204).end();}catch(e){return next(e);}});
export default router;
