// Workspace-routed Trip API.
import { Router } from "express";
import { requireAuth } from "../middleware/auth.js";
import { PERMISSIONS } from "../services/accessCatalog.js";
import { operationalPrismaForWorkspace } from "../services/workspaceOperationalContext.js";
import { canCreateWorkspaceTrip,canDeleteWorkspaceTrip,canReadWorkspaceTrip,canUpdateWorkspaceTrip,workspaceTripReadWhere } from "../services/workspaceAuthorization.js";
const router=Router({mergeParams:true});router.use(requireAuth);
function parseId(v){const id=Number(v);return Number.isInteger(id)&&id>0?id:null;}function nullableNumber(v,f=null){if(v===""||v==null)return f;const p=Number(v);return Number.isFinite(p)?p:f;}function nullableMoney(v,f=null){if(v===""||v==null)return f;const raw=String(v).trim();if(!/^\d+(?:\.\d{1,2})?$/.test(raw)){const e=new Error("price must be a non-negative amount with at most two decimal places");e.status=400;throw e;}const[w,fr=""]=raw.split(".");return`${BigInt(w)}.${fr.padEnd(2,"0")}`;}function nullableDate(v,f){if(v===""||v==null)return null;const p=new Date(v);if(Number.isNaN(p.getTime())){const e=new Error(`${f} must be a valid date`);e.status=400;throw e;}return p;}
function buildTripPatch(body={}){const supported=["tripType","destination","origin","date","departureTime","returnDate","returnTime","students","staff","price","notes","busInfo","driverInfo","buses","boosterSeatsRequested","boosterSeatCount"],patch={};for(const key of supported){if(body[key]===undefined)continue;if(key==="date"||key==="returnDate")patch[key]=nullableDate(body[key],key);else if(["students","staff"].includes(key))patch[key]=nullableNumber(body[key]);else if(key==="price")patch[key]=nullableMoney(body[key],"0.00");else if(key==="boosterSeatCount")patch[key]=nullableNumber(body[key],0);else if(key==="boosterSeatsRequested")patch[key]=Boolean(body[key]);else patch[key]=body[key];}return patch;}function patchPermission(p){const f=Object.keys(p);if(f.length&&f.every(x=>x==="price"))return PERMISSIONS.FINANCE_MANAGE_PRICE;if(f.some(x=>["busInfo","driverInfo","buses"].includes(x)))return PERMISSIONS.TRIP_RESPOND;return PERMISSIONS.TRIP_EDIT_REQUEST;}function schoolTripWhere(s,e=null){const b={owningSchoolOrganizationId:s};return e&&Object.keys(e).length?{AND:[b,e]}:b;}async function findSchoolTrip(p,s,id){return p.trip.findFirst({where:{id,owningSchoolOrganizationId:s}});}function workflowError(m,status=409){const e=new Error(m);e.status=status;return e;}
const transitions={accept:{from:["Pending"],to:"Accepted",permission:PERMISSIONS.TRIP_RESPOND},reject:{from:["Pending"],to:"Rejected",permission:PERMISSIONS.TRIP_RESPOND},confirm:{from:["Approved"],to:"Confirmed",permission:PERMISSIONS.TRIP_RESPOND},complete:{from:["Confirmed"],to:"Completed",permission:PERMISSIONS.TRIP_RESPOND},cancel:{from:["Pending","Accepted","Quotation Submitted","Approved","Confirmed"],to:"Cancelled",permission:PERMISSIONS.TRIP_CANCEL}};
async function lifecycle(req,action){const rule=transitions[action];if(!rule)throw workflowError("Unsupported workflow action",400);const id=parseId(req.params.id);if(!id)throw workflowError("Invalid trip id",400);const{prisma,access,workspace}=await operationalPrismaForWorkspace(req.user,req.params.schoolId,rule.permission);const trip=await findSchoolTrip(prisma,workspace.schoolId,id);if(!trip)throw workflowError("Trip not found",404);if(!canReadWorkspaceTrip({access,workspace,trip}))throw workflowError("Forbidden",403);if(trip.cancelRequest&&action!=="cancel")throw workflowError("This trip has a pending cancellation request");if(!rule.from.includes(trip.status))throw workflowError(`Trip cannot be ${action}ed while its status is ${trip.status}`);const result=await prisma.trip.updateMany({where:{id,owningSchoolOrganizationId:workspace.schoolId,status:trip.status},data:{status:rule.to,...(action==="cancel"?{cancelRequest:false}:{})}});if(result.count!==1)throw workflowError("Trip changed while the action was being processed. Refresh and try again.");return prisma.trip.findUnique({where:{id}});}
router.get("/",async(req,res,next)=>{try{const{prisma,access,workspace}=await operationalPrismaForWorkspace(req.user,req.params.schoolId,PERMISSIONS.TRIP_READ);const scope=workspaceTripReadWhere({access,workspace});if(!scope)return res.status(403).json({message:"Forbidden"});const filters=[scope],createdBy=String(req.query?.createdBy||"").trim();if(createdBy){const needle=createdBy.includes(" ")?createdBy.split(" ")[0]:createdBy;filters.push({createdBy:{contains:needle,mode:"insensitive"}});}const extra=filters.length===1?filters[0]:{AND:filters};return res.json(await prisma.trip.findMany({where:schoolTripWhere(workspace.schoolId,extra),orderBy:{id:"desc"}}));}catch(e){next(e);}});
router.get("/:id",async(req,res,next)=>{try{const id=parseId(req.params.id);if(!id)return res.status(400).json({message:"Invalid trip id"});const{prisma,access,workspace}=await operationalPrismaForWorkspace(req.user,req.params.schoolId,PERMISSIONS.TRIP_READ);const trip=await findSchoolTrip(prisma,workspace.schoolId,id);if(!trip)return res.status(404).json({message:"Trip not found"});if(!canReadWorkspaceTrip({access,workspace,trip}))return res.status(403).json({message:"Forbidden"});res.json(trip);}catch(e){next(e);}});
router.post("/",async(req,res,next)=>{try{const{prisma,access,workspace}=await operationalPrismaForWorkspace(req.user,req.params.schoolId,PERMISSIONS.TRIP_CREATE);if(!canCreateWorkspaceTrip({workspace}))return res.status(403).json({message:"Forbidden"});const b=req.body||{};res.status(201).json(await prisma.trip.create({data:{createdByAppUserId:access.user?.appUserId||null,tenantId:access.tenantId||null,owningSchoolOrganizationId:workspace.schoolId,managingOrganizationId:null,transportProviderOrganizationId:null,createdById:Number.isInteger(Number(req.user.id))?Number(req.user.id):null,createdBy:req.user.name??null,createdByEmail:req.user.email??null,tripType:b.tripType??null,destination:b.destination??null,origin:b.origin??null,date:nullableDate(b.date,"date"),departureTime:b.departureTime??null,returnDate:nullableDate(b.returnDate,"returnDate"),returnTime:b.returnTime??null,students:nullableNumber(b.students),staff:nullableNumber(b.staff),status:"Pending",price:"0.00",notes:b.notes??null,cancelRequest:false,busInfo:null,driverInfo:null,buses:null,boosterSeatsRequested:Boolean(b.boosterSeatsRequested),boosterSeatCount:nullableNumber(b.boosterSeatCount,0)}}));}catch(e){next(e);}});
for(const action of ["accept","reject","confirm","complete","cancel"])router.post(`/:id/${action}`,async(req,res,next)=>{try{res.json(await lifecycle(req,action));}catch(e){next(e);}});
router.post("/:id/cancellation-request",async(req,res,next)=>{try{const id=parseId(req.params.id);const{prisma,access,workspace}=await operationalPrismaForWorkspace(req.user,req.params.schoolId,PERMISSIONS.TRIP_CANCEL);const trip=await findSchoolTrip(prisma,workspace.schoolId,id);if(!trip)return res.status(404).json({message:"Trip not found"});if(!canReadWorkspaceTrip({access,workspace,trip}))return res.status(403).json({message:"Forbidden"});if(["Completed","Cancelled","Rejected"].includes(trip.status))return res.status(409).json({message:`A ${trip.status.toLowerCase()} trip cannot request cancellation`});if(trip.cancelRequest)return res.json(trip);res.json(await prisma.trip.update({where:{id},data:{cancelRequest:true}}));}catch(e){next(e);}});
router.post("/:id/cancellation-decision",async(req,res,next)=>{try{const id=parseId(req.params.id);const{prisma,access,workspace}=await operationalPrismaForWorkspace(req.user,req.params.schoolId,PERMISSIONS.TRIP_RESPOND);const trip=await findSchoolTrip(prisma,workspace.schoolId,id);if(!trip)return res.status(404).json({message:"Trip not found"});if(!canReadWorkspaceTrip({access,workspace,trip}))return res.status(403).json({message:"Forbidden"});if(!trip.cancelRequest)return res.status(409).json({message:"There is no pending cancellation request"});res.json(await prisma.trip.update({where:{id},data:{cancelRequest:false,...(Boolean(req.body?.approve)?{status:"Cancelled"}:{})}}));}catch(e){next(e);}});
router.patch("/:id",async(req,res,next)=>{try{const id=parseId(req.params.id);if(!id)return res.status(400).json({message:"Invalid trip id"});if(req.body?.status!==undefined||req.body?.cancelRequest!==undefined)return res.status(400).json({message:"Trip lifecycle fields must be changed through workflow actions"});const patch=buildTripPatch(req.body||{});if(!Object.keys(patch).length)return res.status(400).json({message:"No supported fields supplied"});const{prisma,access,workspace}=await operationalPrismaForWorkspace(req.user,req.params.schoolId,patchPermission(patch));const existing=await findSchoolTrip(prisma,workspace.schoolId,id);if(!existing)return res.status(404).json({message:"Trip not found"});if(!canUpdateWorkspaceTrip({access,workspace,trip:existing,patch}))return res.status(403).json({message:"Forbidden"});res.json(await prisma.trip.update({where:{id},data:patch}));}catch(e){next(e);}});
router.delete("/:id",async(req,res,next)=>{try{const id=parseId(req.params.id);if(!id)return res.status(400).json({message:"Invalid trip id"});const{prisma,workspace}=await operationalPrismaForWorkspace(req.user,req.params.schoolId,PERMISSIONS.TRIP_DELETE);const existing=await findSchoolTrip(prisma,workspace.schoolId,id);if(!existing)return res.status(404).json({message:"Trip not found"});if(!canDeleteWorkspaceTrip({workspace}))return res.status(403).json({message:"Forbidden"});await prisma.trip.delete({where:{id}});res.json({ok:true});}catch(e){next(e);}});
export default router;
