// Workspace-routed first-class bus assignments. One Trip can have many buses.
import { Router } from "express";
import { requireAuth } from "../middleware/auth.js";
import { PERMISSIONS } from "../services/accessCatalog.js";
import { operationalPrismaForWorkspace } from "../services/workspaceOperationalContext.js";
import { canAllocateWorkspacePassengers, canManageWorkspaceBusAssignments, canReadWorkspaceBusAssignments } from "../services/workspaceAuthorization.js";
const router=Router({mergeParams:true});router.use(requireAuth);
const STATUSES=new Set(["assigned","confirmed","completed","cancelled"]);
const BASE_SELECT={id:true,tripId:true,sequence:true,busType:true,seatCapacity:true,vehicleNumber:true,plateNumber:true,driverName:true,driverPhone:true,price:true,currency:true,status:true,notes:true,createdAt:true,updatedAt:true};
function positiveInt(v,f){const n=Number(v);if(!Number.isInteger(n)||n<=0){const e=new Error(`${f} must be a positive integer`);e.status=400;throw e;}return n;}
function uuid(v,f){const t=String(v||"").trim();if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(t)){const e=new Error(`${f} must be a valid UUID`);e.status=400;throw e;}return t;}
function optionalString(v,f,m){if(v===undefined||v===null||v==="")return null;const t=String(v).trim();if(!t)return null;if(t.length>m){const e=new Error(`${f} is too long`);e.status=400;throw e;}return t;}
function patch(input={},creating=false){const allowed=new Set(["sequence","busType","seatCapacity","vehicleNumber","plateNumber","driverName","driverPhone","price","currency","status","notes"]);const unknown=Object.keys(input).filter(k=>!allowed.has(k));if(unknown.length){const e=new Error(`Unsupported bus assignment fields: ${unknown.join(", ")}`);e.status=400;throw e;}const d={};for(const[f,m]of[["busType",100],["vehicleNumber",120],["plateNumber",80],["driverName",160],["driverPhone",50],["notes",2000]])if(input[f]!==undefined)d[f]=optionalString(input[f],f,m);if(input.sequence!==undefined)d.sequence=positiveInt(input.sequence,"sequence");if(input.seatCapacity!==undefined){const n=Number(input.seatCapacity);if(!Number.isInteger(n)||n<0){const e=new Error("seatCapacity must be a non-negative integer");e.status=400;throw e;}d.seatCapacity=n;}if(input.price!==undefined){const raw=String(input.price).trim();if(!/^\d+(?:\.\d{1,2})?$/.test(raw)){const e=new Error("price must be a non-negative amount with at most two decimal places");e.status=400;throw e;}const[w,fr=""]=raw.split(".");if(w.length>10||(w.length===10&&BigInt(w)>9999999999n)){const e=new Error("price exceeds the supported amount");e.status=400;throw e;}d.price=`${BigInt(w)}.${fr.padEnd(2,"0")}`;}if(input.currency!==undefined){const c=optionalString(input.currency,"currency",3);if(c&&!/^[A-Za-z]{3}$/.test(c)){const e=new Error("currency must be a three-letter currency code");e.status=400;throw e;}d.currency=c?.toUpperCase()||"AED";}if(input.status!==undefined){const s=optionalString(input.status,"status",30)?.toLowerCase();if(!s||!STATUSES.has(s)){const e=new Error("Invalid bus assignment status");e.status=400;throw e;}d.status=s;}if(creating){if(!d.status)d.status="assigned";if(!d.currency)d.currency="AED";}return d;}
async function contextAndTrip(req,p){const tripId=positiveInt(req.params.tripId,"trip id");const c=await operationalPrismaForWorkspace(req.user,req.params.schoolId,p);const trip=await c.prisma.trip.findFirst({where:{id:tripId,owningSchoolOrganizationId:c.workspace.schoolId},select:{id:true,status:true,createdByAppUserId:true}});return{...c,tripId,trip};}
function selectForWorkspace(workspace){const perms=new Set(workspace?.permissions||[]);if(perms.has(PERMISSIONS.BUS_ASSIGNMENT_MANAGE))return BASE_SELECT;if(perms.has(PERMISSIONS.FINANCE_READ))return{...BASE_SELECT,driverPhone:false,driverName:false,notes:false};return{...BASE_SELECT,driverPhone:false,price:false};}
router.get("/",async(req,res,next)=>{try{const{prisma,workspace,tripId,trip}=await contextAndTrip(req,PERMISSIONS.BUS_ASSIGNMENT_READ);if(!trip)return res.status(404).json({message:"Trip not found"});if(!canReadWorkspaceBusAssignments({workspace}))return res.status(403).json({message:"Forbidden"});return res.json(await prisma.tripBusAssignment.findMany({where:{tripId},select:selectForWorkspace(workspace),orderBy:[{sequence:"asc"},{createdAt:"asc"}]}));}catch(e){return next(e);}});
router.post("/",async(req,res,next)=>{try{const{prisma,workspace,tripId,trip}=await contextAndTrip(req,PERMISSIONS.BUS_ASSIGNMENT_MANAGE);if(!trip)return res.status(404).json({message:"Trip not found"});if(!canManageWorkspaceBusAssignments({workspace}))return res.status(403).json({message:"Forbidden"});const data=patch(req.body||{},true);const created=await prisma.$transaction(async tx=>{if(!data.sequence){const last=await tx.tripBusAssignment.findFirst({where:{tripId},select:{sequence:true},orderBy:{sequence:"desc"}});data.sequence=(last?.sequence||0)+1;}return tx.tripBusAssignment.create({data:{tripId,...data},select:BASE_SELECT});});return res.status(201).json(created);}catch(e){if(e?.code==="P2002")return res.status(409).json({message:"Bus assignment sequence already exists; retry the request"});return next(e);}});
router.patch("/:assignmentId",async(req,res,next)=>{try{const assignmentId=uuid(req.params.assignmentId,"assignment id");const{prisma,workspace,tripId,trip}=await contextAndTrip(req,PERMISSIONS.BUS_ASSIGNMENT_MANAGE);if(!trip)return res.status(404).json({message:"Trip not found"});if(!canManageWorkspaceBusAssignments({workspace}))return res.status(403).json({message:"Forbidden"});const data=patch(req.body||{});if(!Object.keys(data).length)return res.status(400).json({message:"No supported fields to update"});const existing=await prisma.tripBusAssignment.findFirst({where:{id:assignmentId,tripId},select:{id:true}});if(!existing)return res.status(404).json({message:"Bus assignment not found"});return res.json(await prisma.tripBusAssignment.update({where:{id:assignmentId},data,select:BASE_SELECT}));}catch(e){if(e?.code==="P2002")return res.status(409).json({message:"Bus assignment sequence already exists"});return next(e);}});
router.delete("/:assignmentId",async(req,res,next)=>{try{const assignmentId=uuid(req.params.assignmentId,"assignment id");const{prisma,workspace,tripId,trip}=await contextAndTrip(req,PERMISSIONS.BUS_ASSIGNMENT_MANAGE);if(!trip)return res.status(404).json({message:"Trip not found"});if(!canManageWorkspaceBusAssignments({workspace}))return res.status(403).json({message:"Forbidden"});const r=await prisma.tripBusAssignment.deleteMany({where:{id:assignmentId,tripId}});if(!r.count)return res.status(404).json({message:"Bus assignment not found"});return res.status(204).end();}catch(e){return next(e);}});
router.put("/:assignmentId/passengers",async(req,res,next)=>{try{const assignmentId=uuid(req.params.assignmentId,"assignment id");const{prisma,access,workspace,tripId,trip}=await contextAndTrip(req,PERMISSIONS.PASSENGER_ALLOCATE);if(!trip)return res.status(404).json({message:"Trip not found"});if(!canAllocateWorkspacePassengers({access,workspace,trip}))return res.status(403).json({message:"Forbidden"});const raw=req.body?.passengerIds;if(!Array.isArray(raw))return res.status(400).json({message:"passengerIds must be an array"});if(raw.length>500)return res.status(400).json({message:"Too many passengers in one allocation request"});const passengerIds=[...new Set(raw.map(id=>positiveInt(id,"passenger id")))];await prisma.$transaction(async tx=>{const a=await tx.tripBusAssignment.findFirst({where:{id:assignmentId,tripId},select:{id:true,seatCapacity:true}});if(!a){const e=new Error("Bus assignment not found");e.status=404;throw e;}if(a.seatCapacity!=null&&passengerIds.length>a.seatCapacity){const e=new Error("Passenger allocation exceeds bus seat capacity");e.status=409;throw e;}const count=passengerIds.length?await tx.tripPassenger.count({where:{tripId,id:{in:passengerIds}}}):0;if(count!==passengerIds.length){const e=new Error("One or more passengers do not belong to this trip");e.status=400;throw e;}const dup=passengerIds.length?await tx.tripBusPassengerAllocation.findFirst({where:{tripPassengerId:{in:passengerIds},tripId,busAssignmentId:{not:assignmentId}},select:{tripPassengerId:true}}):null;if(dup){const e=new Error(`Passenger ${dup.tripPassengerId} is already allocated to another bus on this trip`);e.status=409;throw e;}await tx.tripBusPassengerAllocation.deleteMany({where:{busAssignmentId:assignmentId,tripId}});if(passengerIds.length)await tx.tripBusPassengerAllocation.createMany({data:passengerIds.map(tripPassengerId=>({busAssignmentId:assignmentId,tripPassengerId,tripId}))});});return res.json({assignmentId,passengerIds});}catch(e){if(e?.code==="P2002")return res.status(409).json({message:"One or more passengers are already allocated to another bus on this trip"});return next(e);}});
export default router;
