// Explicit Trip workflow actions. External recipients are represented by scoped
// approval/action records, never by fake AppUsers.
import { Router } from "express";
import { requireAuth } from "../middleware/auth.js";
import { PERMISSIONS } from "../services/accessCatalog.js";
import { operationalPrismaForWorkspace } from "../services/workspaceOperationalContext.js";
import { canApproveWorkspaceQuotation, canConfirmWorkspaceTrip, canReadWorkspaceTrip, canSubmitWorkspaceQuotation } from "../services/workspaceAuthorization.js";
import { EXTERNAL_ACTIONS, issueExternalWorkflowAction } from "../services/externalWorkflowActions.js";
const router=Router({mergeParams:true});router.use(requireAuth);
function positiveInt(value,field){const n=Number(value);if(!Number.isInteger(n)||n<=0)throw Object.assign(new Error(`${field} must be a positive integer`),{status:400});return n;}
function actorId(access){return String(access?.user?.appUserId||"").trim()||null;}function email(value){return String(value||"").trim().toLowerCase();}
async function context(req,permission){const tripId=positiveInt(req.params.tripId,"trip id"),c=await operationalPrismaForWorkspace(req.user,req.params.schoolId,permission),trip=await c.prisma.trip.findFirst({where:{id:tripId,owningSchoolOrganizationId:c.workspace.schoolId},select:{id:true,status:true,createdByAppUserId:true}});return{...c,tripId,trip};}
async function submittedQuotation(prisma,tripId){return prisma.tripQuotation.findFirst({where:{tripId,status:"submitted"},orderBy:{version:"desc"},include:{lines:{orderBy:{sequence:"asc"}}}});}
router.get("/quotation",async(req,res,next)=>{try{const{prisma,access,workspace,tripId,trip}=await context(req,PERMISSIONS.TRIP_READ);if(!trip)return res.status(404).json({message:"Trip not found"});if(!canReadWorkspaceTrip({access,workspace,trip}))return res.status(403).json({message:"Forbidden"});return res.json(await prisma.tripQuotation.findFirst({where:{tripId},orderBy:{version:"desc"},include:{lines:{orderBy:{sequence:"asc"}},approvalRequests:{orderBy:{requestedAt:"desc"}}}}));}catch(e){next(e);}});
router.post("/submit-quotation",async(req,res,next)=>{try{const{prisma,access,workspace,tripId,trip}=await context(req,PERMISSIONS.TRIP_RESPOND);if(!trip)return res.status(404).json({message:"Trip not found"});if(!canSubmitWorkspaceQuotation({workspace,trip}))return res.status(409).json({message:"Trip must be Accepted before its quotation can be submitted"});const result=await prisma.$transaction(async tx=>{const buses=await tx.tripBusAssignment.findMany({where:{tripId,status:{not:"cancelled"}},orderBy:{sequence:"asc"}});if(!buses.length)throw Object.assign(new Error("At least one bus assignment is required before submitting a quotation"),{status:409});for(const bus of buses){if(!String(bus.busType||"").trim())throw Object.assign(new Error(`Bus ${bus.sequence} requires a bus type before quotation submission`),{status:409});if(bus.price==null)throw Object.assign(new Error(`Bus ${bus.sequence} requires a price before quotation submission`),{status:409});}const latest=await tx.tripQuotation.findFirst({where:{tripId},select:{version:true,id:true,status:true},orderBy:{version:"desc"}});if(latest&&latest.status!=="superseded")await tx.tripQuotation.update({where:{id:latest.id},data:{status:"superseded",supersededAt:new Date()}});const quotation=await tx.tripQuotation.create({data:{tripId,version:(latest?.version||0)+1,submittedByAppUserId:actorId(access),lines:{create:buses.map(bus=>({busAssignmentId:bus.id,sequence:bus.sequence,busType:bus.busType.trim(),seatCapacity:bus.seatCapacity,price:bus.price,currency:bus.currency}))}},include:{lines:{orderBy:{sequence:"asc"}}}});await tx.trip.update({where:{id:tripId},data:{status:"Quotation Submitted"}});return quotation;});return res.status(201).json(result);}catch(e){next(e);}});

// Request approval without assuming the approver is a platform user. For an
// external approver we issue a short-lived opaque bearer token; only its digest
// is stored. Delivery is deliberately separate so Outlook/Graph or a platform
// mailer can use the same approval request later.
router.post("/request-approval",async(req,res,next)=>{try{const{prisma,access,workspace,tripId,trip}=await context(req,PERMISSIONS.TRIP_READ);if(!trip)return res.status(404).json({message:"Trip not found"});if(!canReadWorkspaceTrip({access,workspace,trip}))return res.status(403).json({message:"Forbidden"});if(trip.status!=="Quotation Submitted")return res.status(409).json({message:"Approval can only be requested for a submitted quotation"});const quotation=await submittedQuotation(prisma,tripId);if(!quotation)return res.status(409).json({message:"Submitted quotation not found"});const approverAppUserId=String(req.body?.approverAppUserId||"").trim()||null,approverEmail=email(req.body?.approverEmail),external=!approverAppUserId;if(external&&!approverEmail.includes("@"))return res.status(400).json({message:"Choose an internal approver or provide an external approver email"});const result=await prisma.$transaction(async tx=>{await tx.tripApprovalRequest.updateMany({where:{tripId,quotationId:quotation.id,status:"pending"},data:{status:"superseded",decidedAt:new Date(),decisionNote:"Superseded by a newer approval request"}});const approval=await tx.tripApprovalRequest.create({data:{tripId,quotationId:quotation.id,status:"pending",requestedByAppUserId:actorId(access),approverAppUserId,approverEmail:approverEmail||null,channel:external?(req.body?.channel||"email"):"in_app"}});let externalAction=null;if(external){externalAction=await issueExternalWorkflowAction({prisma:tx,tripId,quotationId:quotation.id,approvalRequestId:approval.id,recipientEmail:approverEmail,participantOrganizationId:req.body?.participantOrganizationId||null,allowedActions:[EXTERNAL_ACTIONS.APPROVE_QUOTATION,EXTERNAL_ACTIONS.DECLINE_QUOTATION],channel:req.body?.channel||"email"});}return{approval,externalAction};});return res.status(201).json({approval:result.approval,delivery:result.externalAction?{channel:result.externalAction.action.channel,recipientEmail:result.externalAction.action.recipientEmail,expiresAt:result.externalAction.action.expiresAt,actionToken:result.externalAction.token}:null});}catch(e){next(e);}});

router.post("/approve-quotation",async(req,res,next)=>{try{const{prisma,access,workspace,tripId,trip}=await context(req,PERMISSIONS.TRIP_APPROVE_QUOTE);if(!trip)return res.status(404).json({message:"Trip not found"});if(!canApproveWorkspaceQuotation({workspace,trip}))return res.status(409).json({message:"A submitted quotation is required before approval"});const result=await prisma.$transaction(async tx=>{const quotation=await tx.tripQuotation.findFirst({where:{tripId,status:"submitted"},orderBy:{version:"desc"}});if(!quotation)throw Object.assign(new Error("Submitted quotation not found"),{status:409});const approverAppUserId=actorId(access);let approval=await tx.tripApprovalRequest.findFirst({where:{tripId,quotationId:quotation.id,status:"pending",approverAppUserId},orderBy:{requestedAt:"desc"}});if(approval)approval=await tx.tripApprovalRequest.update({where:{id:approval.id},data:{status:"approved",decidedByAppUserId:approverAppUserId,decidedAt:new Date()}});else approval=await tx.tripApprovalRequest.create({data:{tripId,quotationId:quotation.id,status:"approved",requestedByAppUserId:approverAppUserId,approverAppUserId,decidedByAppUserId:approverAppUserId,decidedAt:new Date(),channel:"in_app"}});await tx.tripQuotation.update({where:{id:quotation.id},data:{status:"approved"}});await tx.tripApprovalRequest.updateMany({where:{quotationId:quotation.id,status:"pending",id:{not:approval.id}},data:{status:"superseded",decidedAt:new Date(),decisionNote:"Quotation approved through another approval request"}});await tx.trip.update({where:{id:tripId},data:{status:"Approved"}});return{quotationId:quotation.id,quotationVersion:quotation.version,approval};});return res.json(result);}catch(e){next(e);}});
router.post("/confirm",async(req,res,next)=>{try{const{prisma,workspace,tripId,trip}=await context(req,PERMISSIONS.TRIP_RESPOND);if(!trip)return res.status(404).json({message:"Trip not found"});if(!canConfirmWorkspaceTrip({workspace,trip}))return res.status(409).json({message:"Trip must have an approved quotation before final confirmation"});const buses=await prisma.tripBusAssignment.findMany({where:{tripId,status:{not:"cancelled"}},select:{sequence:true,driverName:true,driverPhone:true}});if(!buses.length)return res.status(409).json({message:"At least one bus assignment is required before final confirmation"});const incomplete=buses.find(bus=>!String(bus.driverName||"").trim()||!String(bus.driverPhone||"").trim());if(incomplete)return res.status(409).json({message:`Bus ${incomplete.sequence} requires driver name and phone before final confirmation`});await prisma.trip.update({where:{id:tripId},data:{status:"Confirmed"}});return res.json({tripId,status:"Confirmed"});}catch(e){next(e);}});
export default router;
