import React, { useState } from "react";
import { FiEdit2, FiGrid, FiPlus, FiSave, FiX } from "react-icons/fi";
import { toast } from "react-toastify";
import api from "@/services/apiClient";

const TYPES = [["SCHOOL_GROUP","School Group"],["SCHOOL","School"],["BUS_OPERATOR","Bus Operator"],["SERVICE_PARTNER","Service Partner"]];
const typeLabel=(type)=>TYPES.find(([key])=>key===type)?.[1]||type;
const blank={display_name:"",full_name:"",abbreviation:"",type:"SCHOOL"};

function OrganizationEditor({ tenantId, organizations = [], search = "", onChanged }) {
  const [editingId,setEditingId]=useState(null),[showForm,setShowForm]=useState(false),[saving,setSaving]=useState(false),[draft,setDraft]=useState(blank);
  const q=search.trim().toLowerCase();
  const visible=organizations.filter(org=>!q||`${org.display_name||""} ${org.full_name||""} ${org.abbreviation||""} ${org.type||""}`.toLowerCase().includes(q));
  const reset=()=>{setEditingId(null);setShowForm(false);setDraft(blank)};
  const startCreate=()=>{setEditingId(null);setDraft(blank);setShowForm(true)};
  const startEdit=(org)=>{setEditingId(org.id);setDraft({display_name:org.display_name||"",full_name:org.full_name||"",abbreviation:org.abbreviation||"",type:org.type||"SCHOOL"});setShowForm(true)};
  const save=async(event)=>{event.preventDefault();if(!tenantId||!draft.display_name.trim())return;setSaving(true);try{const payload={tenant_id:tenantId,display_name:draft.display_name.trim(),full_name:draft.full_name.trim()||null,abbreviation:draft.abbreviation.trim().toUpperCase()||null,type:draft.type};if(editingId){await api.patch(`/access-admin/organizations/${editingId}`,payload);toast.success("Organization updated")}else{await api.post("/access-admin/organizations",payload);toast.success("Organization created")}reset();await onChanged?.()}catch(error){toast.error(error?.response?.data?.message||"Could not save organization")}finally{setSaving(false)}};
  return <div className="space-y-4">
    <div className="flex flex-col gap-3 rounded-xl bg-slate-50 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="text-sm font-semibold text-slate-900">Organization directory</div><div className="mt-1 text-xs text-slate-500">Manage School Groups, Schools, Bus Operators and Service Partners from the canonical Control Plane.</div></div><button type="button" onClick={showForm?reset:startCreate} className="inline-flex items-center justify-center gap-2 rounded-lg border bg-white px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50">{showForm?<FiX/>:<FiPlus/>} {showForm?"Close":"Add organization"}</button></div>
    {showForm&&<form onSubmit={save} className="rounded-xl border bg-white p-4"><div className="mb-4 flex items-start gap-2"><FiGrid className="mt-0.5 text-violet-600"/><div><div className="text-sm font-semibold text-slate-900">{editingId?"Edit organization":"New organization"}</div><div className="text-xs text-slate-500">Display name is the prominent name used in the interface. Full name appears as supporting detail.</div></div></div><div className="grid gap-3 lg:grid-cols-2">
      <label className="text-sm text-slate-700"><span className="mb-1 block text-xs font-semibold uppercase tracking-wide text-slate-400">Display name</span><input value={draft.display_name} onChange={e=>setDraft(d=>({...d,display_name:e.target.value}))} maxLength={200} placeholder="Repton Dubai" className="w-full rounded-lg border px-3 py-2 outline-none focus:ring-2 focus:ring-violet-500"/></label>
      <label className="text-sm text-slate-700"><span className="mb-1 block text-xs font-semibold uppercase tracking-wide text-slate-400">Full name</span><input value={draft.full_name} onChange={e=>setDraft(d=>({...d,full_name:e.target.value}))} maxLength={200} placeholder="Repton School Dubai" className="w-full rounded-lg border px-3 py-2 outline-none focus:ring-2 focus:ring-violet-500"/><span className="mt-1 block text-xs text-slate-400">Shown below the display name where additional context is useful.</span></label>
      <label className="text-sm text-slate-700"><span className="mb-1 block text-xs font-semibold uppercase tracking-wide text-slate-400">Abbreviation</span><input value={draft.abbreviation} onChange={e=>setDraft(d=>({...d,abbreviation:e.target.value.toUpperCase()}))} maxLength={50} placeholder="RDXB" className="w-full rounded-lg border px-3 py-2 outline-none focus:ring-2 focus:ring-violet-500"/><span className="mt-1 block text-xs text-slate-400">Used in compact tables, reports and calendar views.</span></label>
      <label className="text-sm text-slate-700"><span className="mb-1 block text-xs font-semibold uppercase tracking-wide text-slate-400">Organization type</span><select value={draft.type} onChange={e=>setDraft(d=>({...d,type:e.target.value}))} className="w-full rounded-lg border bg-white px-3 py-2 outline-none focus:ring-2 focus:ring-violet-500">{TYPES.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
    </div><div className="mt-4 flex justify-end border-t pt-4"><button type="submit" disabled={saving||!draft.display_name.trim()} className="inline-flex items-center gap-2 rounded-lg bg-violet-600 px-3 py-2 text-sm font-medium text-white hover:bg-violet-700 disabled:opacity-50"><FiSave/> {saving?"Saving…":editingId?"Save changes":"Create organization"}</button></div></form>}
    <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{visible.map(org=><article key={org.id} className="rounded-xl border bg-white p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex items-start gap-2">{org.abbreviation?<span className="shrink-0 rounded-md bg-slate-100 px-2 py-1 text-xs font-semibold text-slate-600">{org.abbreviation}</span>:null}<div className="min-w-0"><div className="font-semibold text-slate-900">{org.display_name}</div>{org.full_name&&org.full_name!==org.display_name?<div className="mt-0.5 text-xs text-slate-500">{org.full_name}</div>:null}</div></div><div className="mt-3 text-xs text-slate-500">{typeLabel(org.type)}</div></div><button type="button" onClick={()=>startEdit(org)} className="inline-flex items-center gap-1.5 rounded-lg border px-2.5 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-50"><FiEdit2/> Edit</button></div></article>)}</div>
    {!visible.length?<div className="rounded-xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">No organizations match this search.</div>:null}
  </div>;
}
export default OrganizationEditor;
