import React,{useEffect,useMemo,useState}from"react";import{FiPlus,FiSave,FiTrash2,FiX,FiCheck}from"react-icons/fi";import{toast}from"react-toastify";import api from"@/services/apiClient";
const STATUSES=["ACTIVE","PENDING","SUSPENDED","REVOKED"];
function Btn({children,danger=false,disabled=false,onClick,type="button"}){return <button type={type} onClick={onClick} disabled={disabled} className={`inline-flex items-center justify-center gap-1.5 rounded-lg border px-2.5 py-1.5 text-xs font-medium disabled:opacity-50 ${danger?"border-red-200 text-red-700 hover:bg-red-50":"bg-white text-slate-700 hover:bg-slate-50"}`}>{children}</button>}
export default function UserAccessEditor({user,memberships,roleAssignments=[],organizations,roles=[],tenantId,onChanged}){
 const[showMembership,setShowMembership]=useState(false),[showRole,setShowRole]=useState(false),[busy,setBusy]=useState(null),[grants,setGrants]=useState([]),[membershipDraft,setMembershipDraft]=useState({organization_id:"",status:"ACTIVE",is_primary:false}),[roleDraft,setRoleDraft]=useState({role:"",scope_type:"ORGANIZATION",organization_id:""});
 const orgById=useMemo(()=>new Map(organizations.map(o=>[o.id,o])),[organizations]),roleLabels=useMemo(()=>new Map(roles.map(r=>[r.key,r.name])),[roles]);const refresh=async()=>onChanged&&onChanged();
 const loadGrants=async()=>{const active=memberships.filter(m=>m.status==="ACTIVE");const rows=await Promise.all(active.map(async m=>{try{const r=await api.get("/access-admin/permission-grants",{params:{organization_id:m.organization_id}});return(Array.isArray(r.data)?r.data:[]).filter(g=>g.user_id===user.id)}catch{return[]}}));setGrants(rows.flat())};useEffect(()=>{loadGrants()},[user.id,memberships.map(m=>`${m.id}:${m.status}`).join("|")]);
 const addMembership=async e=>{e.preventDefault();if(!membershipDraft.organization_id)return toast.error("Choose an organization");setBusy("membership-add");try{await api.post("/access-admin/memberships",{user_id:user.id,...membershipDraft});toast.success("Membership added");setShowMembership(false);setMembershipDraft({organization_id:"",status:"ACTIVE",is_primary:false});await refresh()}catch(x){toast.error(x?.response?.data?.message||"Could not add membership")}finally{setBusy(null)}};
 const patchMembership=async(m,patch)=>{setBusy(m.id);try{await api.patch(`/access-admin/memberships/${m.id}`,patch);await refresh()}catch(x){toast.error(x?.response?.data?.message||"Could not update membership")}finally{setBusy(null)}};
 const removeMembership=async m=>{if(!window.confirm(`Remove ${user.display_name} from ${m.organization?.display_name||"this organization"}?`))return;setBusy(m.id);try{await api.delete(`/access-admin/memberships/${m.id}`);toast.success("Membership removed");await refresh()}catch(x){toast.error(x?.response?.data?.message||"Could not remove membership")}finally{setBusy(null)}};
 const addRole=async e=>{e.preventDefault();if(!roleDraft.role)return toast.error("Choose a role");const p={user_id:user.id,role:roleDraft.role,scope_type:roleDraft.scope_type};if(roleDraft.scope_type==="TENANT")p.tenant_id=tenantId;if(roleDraft.scope_type==="ORGANIZATION"){if(!roleDraft.organization_id)return toast.error("Choose an organization");p.organization_id=roleDraft.organization_id}setBusy("role-add");try{await api.post("/access-admin/role-assignments",p);toast.success("Role assigned");setShowRole(false);setRoleDraft({role:"",scope_type:"ORGANIZATION",organization_id:""});await refresh()}catch(x){toast.error(x?.response?.data?.message||"Could not assign role")}finally{setBusy(null)}};
 const removeRole=async a=>{if(!window.confirm(`Remove the ${roleLabels.get(a.role)||a.role} role?`))return;setBusy(a.id);try{await api.delete(`/access-admin/role-assignments/${a.id}`);toast.success("Role removed");await refresh()}catch(x){toast.error(x?.response?.data?.message||"Could not remove role")}finally{setBusy(null)}};
 const approvalGrant=orgId=>grants.find(g=>g.organization_id===orgId&&g.permission==="trip.approve_quote");
 const toggleApproval=async m=>{const existing=approvalGrant(m.organization_id);setBusy(`approval-${m.organization_id}`);try{if(existing){if(!window.confirm(`Remove quotation approval authority for ${user.display_name} in ${m.organization?.display_name}?`))return;await api.delete(`/access-admin/permission-grants/${existing.id}`);toast.success("Approval authority removed")}else{await api.post("/access-admin/permission-grants",{user_id:user.id,organization_id:m.organization_id,permission:"trip.approve_quote"});toast.success("Approval authority granted")}await loadGrants()}catch(x){toast.error(x?.response?.data?.message||"Could not update approval authority")}finally{setBusy(null)}};
 return <div className="mt-4 grid gap-4 xl:grid-cols-2">
 <section className="rounded-xl bg-slate-50 p-3"><div className="mb-3 flex items-center justify-between"><div><div className="text-xs font-semibold uppercase tracking-wide text-slate-400">Organization memberships</div><div className="mt-1 text-xs text-slate-500">Where this user belongs.</div></div><Btn onClick={()=>setShowMembership(v=>!v)}>{showMembership?<FiX/>:<FiPlus/>}{showMembership?"Cancel":"Add"}</Btn></div>
 {showMembership&&<form onSubmit={addMembership} className="mb-3 grid gap-2 rounded-lg border bg-white p-3 sm:grid-cols-2"><select value={membershipDraft.organization_id} onChange={e=>setMembershipDraft(d=>({...d,organization_id:e.target.value}))} className="rounded-lg border px-2.5 py-2 text-sm"><option value="">Choose organization</option>{organizations.map(o=><option key={o.id} value={o.id}>{o.display_name}</option>)}</select><select value={membershipDraft.status} onChange={e=>setMembershipDraft(d=>({...d,status:e.target.value}))} className="rounded-lg border px-2.5 py-2 text-sm">{STATUSES.map(s=><option key={s}>{s}</option>)}</select><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={membershipDraft.is_primary} onChange={e=>setMembershipDraft(d=>({...d,is_primary:e.target.checked}))}/>Primary membership</label><Btn type="submit"><FiSave/>Save</Btn></form>}
 <div className="space-y-2">{memberships.map(m=><div key={m.id} className="rounded-lg border bg-white p-3"><div className="flex items-start justify-between gap-3"><div><div className="font-medium">{m.organization?.display_name}</div><div className="text-xs text-slate-500">{m.is_primary?"Primary · ":""}{m.status}</div></div><Btn danger onClick={()=>removeMembership(m)}><FiTrash2/>Remove</Btn></div><select value={m.status} disabled={busy===m.id} onChange={e=>patchMembership(m,{status:e.target.value})} className="mt-3 w-full rounded-lg border px-2.5 py-2 text-sm">{STATUSES.map(s=><option key={s}>{s}</option>)}</select>{m.status==="ACTIVE"&&m.organization?.type==="SCHOOL"&&<div className="mt-3 flex items-center justify-between rounded-lg border border-violet-100 bg-violet-50/50 p-3"><div><div className="text-sm font-medium text-slate-800">Approve trip quotations</div><div className="text-xs text-slate-500">May approve quotations for this school, including own requested trips.</div></div><button type="button" disabled={busy===`approval-${m.organization_id}`} onClick={()=>toggleApproval(m)} className={`ml-3 inline-flex shrink-0 items-center gap-1 rounded-lg px-2.5 py-1.5 text-xs font-semibold ${approvalGrant(m.organization_id)?"bg-violet-600 text-white":"border bg-white text-slate-700"}`}>{approvalGrant(m.organization_id)&&<FiCheck/>}{approvalGrant(m.organization_id)?"Granted":"Grant"}</button></div>}</div>)}{!memberships.length&&<div className="text-sm text-slate-400">No organization memberships</div>}</div></section>
 <section className="rounded-xl bg-slate-50 p-3"><div className="mb-3 flex items-center justify-between"><div><div className="text-xs font-semibold uppercase tracking-wide text-slate-400">Role assignments</div><div className="mt-1 text-xs text-slate-500">Baseline access by scope.</div></div><Btn onClick={()=>setShowRole(v=>!v)}>{showRole?<FiX/>:<FiPlus/>}{showRole?"Cancel":"Assign"}</Btn></div>
 {showRole&&<form onSubmit={addRole} className="mb-3 grid gap-2 rounded-lg border bg-white p-3"><select value={roleDraft.role} onChange={e=>setRoleDraft(d=>({...d,role:e.target.value}))} className="rounded-lg border px-2.5 py-2 text-sm"><option value="">Choose role</option>{roles.map(r=><option key={r.key} value={r.key}>{r.name}</option>)}</select><select value={roleDraft.scope_type} onChange={e=>setRoleDraft(d=>({...d,scope_type:e.target.value,organization_id:""}))} className="rounded-lg border px-2.5 py-2 text-sm"><option value="ORGANIZATION">Organization</option><option value="TENANT">Tenant</option><option value="PLATFORM">Platform</option></select>{roleDraft.scope_type==="ORGANIZATION"&&<select value={roleDraft.organization_id} onChange={e=>setRoleDraft(d=>({...d,organization_id:e.target.value}))} className="rounded-lg border px-2.5 py-2 text-sm"><option value="">Choose organization</option>{memberships.filter(m=>m.status==="ACTIVE").map(m=><option key={m.organization_id} value={m.organization_id}>{m.organization?.display_name}</option>)}</select>}<Btn type="submit"><FiSave/>Assign role</Btn></form>}
 <div className="space-y-2">{roleAssignments.map(a=>{const org=orgById.get(a.organization_id),scope=a.scope_type==="PLATFORM"?"Platform":a.scope_type==="TENANT"?"Tenant":org?.display_name||"Organization";return <div key={a.id} className="flex items-center justify-between rounded-lg border bg-white p-3"><div><div className="font-medium">{roleLabels.get(a.role)||a.role}</div><div className="text-xs text-slate-500">{scope} · {a.is_active?"Active":"Inactive"}</div></div><Btn danger onClick={()=>removeRole(a)}><FiTrash2/>Remove</Btn></div>})}{!roleAssignments.length&&<div className="text-sm text-slate-400">No role assignments</div>}</div></section></div>;
}
