import test from "node:test";
import assert from "node:assert/strict";
import { PERMISSIONS } from "../src/services/accessCatalog.js";
import { resolveEffectiveAccessV2 } from "../src/services/effectiveAccessV2.js";
function fakePrisma({user,relationships=[],schools=[]}){return{appUser:{findFirst:async()=>user},organizationRelationship:{findMany:async({where})=>relationships.filter(row=>row.toOrganizationId===where.toOrganizationId&&row.type===where.type)},organization:{findMany:async({where})=>schools.filter(row=>row.tenantId===where.tenantId&&row.type===where.type&&row.status===where.status)}};}const school=(id,name=id)=>({id,tenantId:"t1",type:"SCHOOL",displayName:name,fullName:name,abbreviation:id.toUpperCase(),parentId:null,status:"active"});const org=(id,type)=>({id,tenantId:"t1",type,displayName:id,fullName:id,abbreviation:null,parentId:null,status:"active"});function activeUser({memberships=[],assignments=[]}={}){return{id:"u1",legacyUserId:7,email:"u@example.com",displayName:"User",status:"active",memberships,roleAssignments:assignments};}function membership(organization){return{organizationId:organization.id,status:"ACTIVE",organization};}function assignment(role,organization){return{isActive:true,scopeType:"ORGANIZATION",organizationId:organization.id,tenantId:null,role:{key:role},organization,tenant:null};}function tenantAssignment(role,tenantId="t1"){return{isActive:true,scopeType:"TENANT",organizationId:null,tenantId,role:{key:role},organization:null,tenant:{id:tenantId}};}
test("direct school assignment resolves only that school and its permissions",async()=>{const s1=school("s1","School One"),prisma=fakePrisma({user:activeUser({memberships:[membership(s1)],assignments:[assignment("school_staff",s1)]})}),access=await resolveEffectiveAccessV2(prisma,{id:7,email:"u@example.com"});assert.deepEqual(access.workspaces.map(row=>row.schoolId),["s1"]);assert.ok(access.workspaces[0].permissions.includes(PERMISSIONS.TRIP_CREATE));assert.equal(access.workspaces[0].permissions.includes(PERMISSIONS.BUS_ASSIGNMENT_MANAGE),false);});
test("direct group remains visible while its linked schools become workspaces",async()=>{const group=org("g1","SCHOOL_GROUP"),s1=school("s1"),prisma=fakePrisma({user:activeUser({memberships:[membership(group)],assignments:[assignment("group_staff",group)]}),relationships:[{toOrganizationId:"g1",type:"BELONGS_TO_GROUP",status:"active",fromOrganization:s1}]}),access=await resolveEffectiveAccessV2(prisma,{id:7});assert.deepEqual(access.workspaces.map(row=>row.schoolId),["s1"]);assert.deepEqual(new Set(access.organizations.map(row=>row.id)),new Set(["g1","s1"]));});
test("restrictive school assignment remains valid through same-tenant group membership",async()=>{const group=org("g1","SCHOOL_GROUP"),s1=school("s1"),prisma=fakePrisma({user:activeUser({memberships:[membership(group)],assignments:[assignment("school_staff",s1)]})}),access=await resolveEffectiveAccessV2(prisma,{id:7,email:"u@example.com"});assert.deepEqual(access.workspaces.map(row=>row.schoolId),["s1"]);});
test("school finance can be restricted to selected schools",async()=>{const group=org("g1","SCHOOL_GROUP"),s1=school("s1"),s2=school("s2"),prisma=fakePrisma({user:activeUser({memberships:[membership(group)],assignments:[assignment("finance",s1),assignment("finance",s2)]})}),access=await resolveEffectiveAccessV2(prisma,{id:7});assert.deepEqual(access.workspaces.map(row=>row.schoolId),["s1","s2"]);for(const ws of access.workspaces){assert.deepEqual(ws.roles,["finance"]);assert.ok(ws.permissions.includes(PERMISSIONS.FINANCE_READ));}});
test("group finance inherits finance across schools rather than group staff",async()=>{const group=org("g1","SCHOOL_GROUP"),s1=school("s1"),s2=school("s2"),relationships=[s1,s2].map(fromOrganization=>({toOrganizationId:"g1",type:"BELONGS_TO_GROUP",status:"active",fromOrganization})),prisma=fakePrisma({user:activeUser({memberships:[membership(group)],assignments:[assignment("finance",group)]}),relationships}),access=await resolveEffectiveAccessV2(prisma,{id:7});assert.equal(access.workspaces.length,2);for(const ws of access.workspaces){assert.deepEqual(ws.roles,["finance"]);assert.ok(ws.permissions.includes(PERMISSIONS.FINANCE_MANAGE_PRICE));assert.equal(ws.permissions.includes(PERMISSIONS.TRIP_CREATE),false);}});
test("bus operator finance reaches linked schools with finance but not operator powers",async()=>{const operator=org("b1","BUS_OPERATOR"),s1=school("s1"),prisma=fakePrisma({user:activeUser({memberships:[membership(operator)],assignments:[assignment("finance",operator)]}),relationships:[{toOrganizationId:"b1",type:"TRANSPORT_PROVIDER",status:"active",fromOrganization:s1}]}),access=await resolveEffectiveAccessV2(prisma,{id:7});assert.deepEqual(access.workspaces[0].roles,["finance"]);assert.ok(access.workspaces[0].permissions.includes(PERMISSIONS.FINANCE_READ));assert.equal(access.workspaces[0].permissions.includes(PERMISSIONS.BUS_ASSIGNMENT_MANAGE),false);});
test("service partner finance reaches managed schools with finance scope",async()=>{const partner=org("p1","SERVICE_PARTNER"),s1=school("s1"),prisma=fakePrisma({user:activeUser({memberships:[membership(partner)],assignments:[assignment("finance",partner)]}),relationships:[{toOrganizationId:"p1",type:"TRIP_MANAGER",status:"active",fromOrganization:s1}]}),access=await resolveEffectiveAccessV2(prisma,{id:7});assert.deepEqual(access.workspaces[0].roles,["finance"]);assert.ok(access.workspaces[0].permissions.includes(PERMISSIONS.FINANCE_READ));assert.equal(access.workspaces[0].permissions.includes(PERMISSIONS.TRIP_CREATE),false);});
test("tenant finance receives finance scope across active tenant schools",async()=>{const s1=school("s1"),s2=school("s2"),prisma=fakePrisma({user:activeUser({assignments:[tenantAssignment("finance")]}),schools:[s1,s2]}),access=await resolveEffectiveAccessV2(prisma,{id:7});assert.equal(access.workspaces.length,2);for(const ws of access.workspaces)assert.deepEqual(ws.roles,["finance"]);});
test("bus operator reaches only schools linked by active transport relationship and remains visible",async()=>{const operator=org("b1","BUS_OPERATOR"),s1=school("s1"),s2=school("s2"),prisma=fakePrisma({user:activeUser({memberships:[membership(operator)],assignments:[assignment("bus_operator",operator)]}),relationships:[{toOrganizationId:"b1",type:"TRANSPORT_PROVIDER",status:"active",fromOrganization:s1},{toOrganizationId:"b1",type:"TRANSPORT_PROVIDER",status:"inactive",fromOrganization:s2}]}),access=await resolveEffectiveAccessV2(prisma,{id:7,email:"u@example.com"});assert.deepEqual(access.workspaces.map(row=>row.schoolId),["s1"]);assert.ok(access.workspaces[0].permissions.includes(PERMISSIONS.BUS_ASSIGNMENT_MANAGE));});
test("service partner requires active TRIP_MANAGER relationship",async()=>{const partner=org("p1","SERVICE_PARTNER"),s1=school("s1"),prisma=fakePrisma({user:activeUser({memberships:[membership(partner)],assignments:[assignment("service_partner",partner)]}),relationships:[{toOrganizationId:"p1",type:"TRIP_MANAGER",status:"active",fromOrganization:s1}]}),access=await resolveEffectiveAccessV2(prisma,{id:7,email:"u@example.com"});assert.deepEqual(access.workspaces.map(row=>row.schoolId),["s1"]);});
test("inactive user receives no canonical access",async()=>{const prisma=fakePrisma({user:{...activeUser(),status:"inactive"}}),access=await resolveEffectiveAccessV2(prisma,{id:7,email:"u@example.com"});assert.deepEqual(access.workspaces,[]);assert.deepEqual(access.organizations,[]);assert.deepEqual(access.permissions,[]);});
