// Pure planning helpers for the legacy-global -> canonical-v2 access migration.
// IMPORTANT: this module does not write to PostgreSQL.

import { legacyCompatibleRoleKey } from "./accessCatalog.js";
import { canonicalOrganizationType, CANONICAL_ORGANIZATION_TYPES } from "../lib/legacyOrganizations.js";

const ACTIVE_MEMBERSHIP_STATUSES = new Set(["active", "approved"]);
const AMBIGUOUS_LEGACY_ROLES = new Set(["trip_manager"]);

export function canonicalMembershipStatus(value) { const normalized=String(value||"").trim().toLowerCase(); if(ACTIVE_MEMBERSHIP_STATUSES.has(normalized))return "ACTIVE"; if(normalized==="pending")return "PENDING"; if(normalized==="blocked"||normalized==="suspended")return "SUSPENDED"; if(normalized==="revoked")return "REVOKED"; return "PENDING"; }
export function planTenants(rows=[]){return rows.map(row=>({id:row.id,name:row.name,slug:row.slug,status:row.status||"active",timezone:row.timezone||"Asia/Dubai"}));}
export function planOrganizations(rows=[]){return rows.map(row=>({id:row.id,tenantId:row.tenantId,type:canonicalOrganizationType(row.type),displayName:row.name,fullName:row.name,legalName:null,abbreviation:row.code||null,slug:row.slug,status:"active",parentId:row.parentOrgId||null}));}
export function planAppUsers(rows=[]){return rows.map(row=>({id:row.id,email:row.email,displayName:row.fullName||row.email,status:row.isActive===false?"inactive":"active",legacyUserId:row.legacyUserId??null}));}
function membershipKey(row){return `${row.userId}:${row.orgId}`;}
export function planMemberships(rows=[]){const grouped=new Map();for(const row of rows){const key=membershipKey(row);const current=grouped.get(key)||{userId:row.userId,organizationId:row.orgId,statuses:[],isPrimary:false};current.statuses.push(canonicalMembershipStatus(row.status));current.isPrimary||=Boolean(row.isDefault);grouped.set(key,current);}const rank={ACTIVE:4,PENDING:3,SUSPENDED:2,REVOKED:1};return[...grouped.values()].map(row=>({userId:row.userId,organizationId:row.organizationId,status:row.statuses.sort((a,b)=>rank[b]-rank[a])[0]||"PENDING",isPrimary:row.isPrimary}));}
function scopedSchoolMap(scopes=[]){const map=new Map();for(const scope of scopes){const legacyRole=String(scope.role||"").trim().toLowerCase();if(AMBIGUOUS_LEGACY_ROLES.has(legacyRole))continue;const role=legacyCompatibleRoleKey(scope.role);if(!role)continue;const key=`${scope.userId}:${scope.orgId}:${role}`;const set=map.get(key)||new Set();set.add(scope.schoolOrgId);map.set(key,set);}return map;}
export function findAmbiguousLegacyRoleMemberships(rows=[]){return rows.filter(row=>canonicalMembershipStatus(row.status)==="ACTIVE"&&AMBIGUOUS_LEGACY_ROLES.has(String(row.role||"").trim().toLowerCase())).map(row=>({userId:row.userId,organizationId:row.orgId,legacyRole:String(row.role).trim().toLowerCase()}));}
export function planRoleAssignments(memberships=[],scopes=[]){const scopeMap=scopedSchoolMap(scopes),planned=[],seen=new Set();const push=a=>{const key=[a.userId,a.roleKey,a.scopeType,a.tenantId||"",a.organizationId||""].join(":");if(!seen.has(key)){seen.add(key);planned.push(a);}};for(const membership of memberships){if(canonicalMembershipStatus(membership.status)!=="ACTIVE")continue;const legacyRole=String(membership.role||"").trim().toLowerCase();if(AMBIGUOUS_LEGACY_ROLES.has(legacyRole))continue;const roleKey=legacyCompatibleRoleKey(membership.role);if(!roleKey)continue;const schoolScopes=scopeMap.get(`${membership.userId}:${membership.orgId}:${roleKey}`);if(schoolScopes?.size){for(const organizationId of schoolScopes)push({userId:membership.userId,roleKey,scopeType:"ORGANIZATION",tenantId:null,organizationId,isActive:true,source:"legacy_school_scope"});continue;}push({userId:membership.userId,roleKey,scopeType:"ORGANIZATION",tenantId:null,organizationId:membership.orgId,isActive:true,source:"legacy_membership"});}return planned;}
export function planRelationships(orgs=[],partnerships=[]){const organizations=new Map(orgs.map(row=>[row.id,row])),planned=[];for(const org of orgs){if(!org.parentOrgId||canonicalOrganizationType(org.type)!==CANONICAL_ORGANIZATION_TYPES.SCHOOL)continue;planned.push({id:`hierarchy:${org.id}:${org.parentOrgId}`,fromOrganizationId:org.id,toOrganizationId:org.parentOrgId,type:"BELONGS_TO_GROUP",status:"active",notes:"Backfilled from legacy organization parent"});}for(const p of partnerships){const school=organizations.get(p.schoolOrgId),operator=organizations.get(p.busCompanyOrgId);if(!school||!operator)continue;planned.push({id:p.id,fromOrganizationId:p.schoolOrgId,toOrganizationId:p.busCompanyOrgId,type:"TRANSPORT_PROVIDER",status:String(p.status||"active").toLowerCase(),notes:p.notes||null});}return planned;}
export function validateBackfillPlan(plan){const errors=[],tenantIds=new Set(plan.tenants.map(r=>r.id)),userIds=new Set(plan.users.map(r=>r.id)),orgIds=new Set(plan.organizations.map(r=>r.id));for(const org of plan.organizations){if(!tenantIds.has(org.tenantId))errors.push(`Organization ${org.id} references missing tenant ${org.tenantId}`);if(org.parentId&&!orgIds.has(org.parentId))errors.push(`Organization ${org.id} references missing parent ${org.parentId}`);}for(const m of plan.memberships){if(!userIds.has(m.userId))errors.push(`Membership references missing user ${m.userId}`);if(!orgIds.has(m.organizationId))errors.push(`Membership references missing organization ${m.organizationId}`);}for(const a of plan.roleAssignments){if(!userIds.has(a.userId))errors.push(`Role assignment references missing user ${a.userId}`);if(a.organizationId&&!orgIds.has(a.organizationId))errors.push(`Role assignment references missing organization ${a.organizationId}`);}for(const r of plan.relationships){if(!orgIds.has(r.fromOrganizationId))errors.push(`Relationship references missing source ${r.fromOrganizationId}`);if(!orgIds.has(r.toOrganizationId))errors.push(`Relationship references missing target ${r.toOrganizationId}`);}for(const u of plan.unresolvedLegacyRoles||[])errors.push(`Ambiguous legacy role ${u.legacyRole} for user ${u.userId} at organization ${u.organizationId} requires explicit mapping`);return errors;}
export function buildAccessV2BackfillPlan({tenants=[],organizations=[],users=[],memberships=[],scopes=[],partnerships=[]}={}){const plan={tenants:planTenants(tenants),organizations:planOrganizations(organizations),users:planAppUsers(users),memberships:planMemberships(memberships),roleAssignments:planRoleAssignments(memberships,scopes),relationships:planRelationships(organizations,partnerships),unresolvedLegacyRoles:findAmbiguousLegacyRoleMemberships(memberships)};return{...plan,errors:validateBackfillPlan(plan)};}
