// Canonical effective-access resolver. Operational access is derived from
// organization membership, role assignments and organization relationships.
import { permissionsForRoles, ROLE_KEYS } from "./accessCatalog.js";
function activeStatus(v){return String(v||"").trim().toLowerCase()==="active";}function activeMembership(r){return String(r?.status||"").trim().toUpperCase()==="ACTIVE";}function activeRelationship(r,now=new Date()){if(!activeStatus(r?.status))return false;if(r.validFrom&&new Date(r.validFrom)>now)return false;if(r.validUntil&&new Date(r.validUntil)<now)return false;return true;}
function orgView(org){return{id:org.id,type:org.type,displayName:org.displayName,fullName:org.fullName||org.displayName,abbreviation:org.abbreviation||null};}
function addWorkspace(map,org,role,detail){if(!org||org.type!=="SCHOOL"||!role)return;const c=map.get(org.id)||{organization:orgView(org),roles:new Set(),access:[]};c.roles.add(role);const s=JSON.stringify(detail);if(!c.access.some(x=>JSON.stringify(x)===s))c.access.push(detail);map.set(org.id,c);}function addOrganization(map,org,detail){if(!org)return;const c=map.get(org.id)||{organization:orgView(org),access:[]};const s=JSON.stringify(detail);if(!c.access.some(x=>JSON.stringify(x)===s))c.access.push(detail);map.set(org.id,c);}function roleKey(a){return a?.role?.key||null;}
function inheritedGroupRole(r){if(r===ROLE_KEYS.FINANCE)return ROLE_KEYS.FINANCE;if(r===ROLE_KEYS.TENANT_ADMIN)return ROLE_KEYS.TENANT_ADMIN;return ROLE_KEYS.GROUP_STAFF;}function inheritedOperatorRole(r){return r===ROLE_KEYS.FINANCE?ROLE_KEYS.FINANCE:ROLE_KEYS.BUS_OPERATOR;}function inheritedPartnerRole(r){return r===ROLE_KEYS.FINANCE?ROLE_KEYS.FINANCE:ROLE_KEYS.SERVICE_PARTNER;}
export async function resolveEffectiveAccessV2(prisma,identity,{now=new Date()}={}){if(!prisma)throw new Error("Canonical control-plane Prisma client is required");const legacyUserId=Number(identity?.id),email=String(identity?.email||"").trim();const user=await prisma.appUser.findFirst({where:{OR:[...(Number.isInteger(legacyUserId)&&legacyUserId>0?[{legacyUserId}]:[]),...(email?[{email}]:[])]},include:{memberships:{include:{organization:true}},roleAssignments:{include:{role:true,organization:true,tenant:true}}}});if(!user||!activeStatus(user.status))return{source:"canonical-v2",user:user?{id:String(identity?.id||""),appUserId:user.id,email:user.email,displayName:user.displayName}:null,roles:[],permissions:[],organizations:[],workspaces:[],portfolio:{enabled:false,schoolCount:0}};
const memberships=(user.memberships||[]).filter(activeMembership),memberOrgIds=new Set(memberships.map(x=>x.organizationId)),assignments=(user.roleAssignments||[]).filter(x=>x.isActive&&roleKey(x)),platformAssignments=assignments.filter(x=>x.scopeType==="PLATFORM"),organizationAssignments=assignments.filter(x=>x.scopeType==="ORGANIZATION"&&x.organizationId),validAssignments=organizationAssignments.filter(a=>memberOrgIds.has(a.organizationId));const workspaceMap=new Map(),organizationMap=new Map();
for(const a of validAssignments){addOrganization(organizationMap,a.organization,{kind:"direct",role:roleKey(a),viaOrganizationId:a.organizationId});if(a.organization?.type==="SCHOOL")addWorkspace(workspaceMap,a.organization,roleKey(a),{kind:"direct",role:roleKey(a),viaOrganizationId:a.organizationId});}
for(const a of validAssignments.filter(x=>x.organization?.type==="SCHOOL_GROUP")){const rows=await prisma.organizationRelationship.findMany({where:{toOrganizationId:a.organizationId,type:"BELONGS_TO_GROUP"},include:{fromOrganization:true}});for(const r of rows.filter(x=>activeRelationship(x,now))){const role=inheritedGroupRole(roleKey(a)),detail={kind:"relationship",role,viaOrganizationId:a.organizationId,viaRelationship:"BELONGS_TO_GROUP"};addWorkspace(workspaceMap,r.fromOrganization,role,detail);addOrganization(organizationMap,r.fromOrganization,detail);}}
for(const a of validAssignments.filter(x=>x.organization?.type==="BUS_OPERATOR")){const rows=await prisma.organizationRelationship.findMany({where:{toOrganizationId:a.organizationId,type:"TRANSPORT_PROVIDER"},include:{fromOrganization:true}});for(const r of rows.filter(x=>activeRelationship(x,now))){const role=inheritedOperatorRole(roleKey(a)),detail={kind:"relationship",role,viaOrganizationId:a.organizationId,viaRelationship:"TRANSPORT_PROVIDER"};addWorkspace(workspaceMap,r.fromOrganization,role,detail);addOrganization(organizationMap,r.fromOrganization,detail);}}
for(const a of validAssignments.filter(x=>x.organization?.type==="SERVICE_PARTNER")){const rows=await prisma.organizationRelationship.findMany({where:{toOrganizationId:a.organizationId,type:"TRIP_MANAGER"},include:{fromOrganization:true}});for(const r of rows.filter(x=>activeRelationship(x,now))){const role=inheritedPartnerRole(roleKey(a)),detail={kind:"relationship",role,viaOrganizationId:a.organizationId,viaRelationship:"TRIP_MANAGER"};addWorkspace(workspaceMap,r.fromOrganization,role,detail);addOrganization(organizationMap,r.fromOrganization,detail);}}
const workspaces=[...workspaceMap.values()].sort((a,b)=>a.organization.displayName.localeCompare(b.organization.displayName)).map(({organization,roles,access})=>{const rs=[...roles].sort();return{schoolId:organization.id,displayName:organization.displayName,fullName:organization.fullName,abbreviation:organization.abbreviation,roles:rs,permissions:permissionsForRoles(rs),access};});const roles=[...new Set(assignments.map(roleKey).filter(Boolean))].sort(),organizations=[...organizationMap.values()].sort((a,b)=>a.organization.displayName.localeCompare(b.organization.displayName)).map(({organization,access})=>({...organization,access}));return{source:"canonical-v2",user:{id:String(identity?.id||""),appUserId:user.id,email:user.email,displayName:user.displayName},roles,permissions:permissionsForRoles([...roles,...platformAssignments.map(roleKey)]),organizations,workspaces,portfolio:{enabled:workspaces.length>0,schoolCount:workspaces.length}};}
