// Canonical v2 effective-access resolver for the dedicated control plane.
// Roles describe function; assignments and relationships describe scope.
import { permissionsForRoles, ROLE_KEYS } from "./accessCatalog.js";
function activeStatus(value){return String(value||"").trim().toLowerCase()==="active";}function activeMembership(row){return String(row?.status||"").trim().toUpperCase()==="ACTIVE";}function activeRelationship(row,now=new Date()){if(!activeStatus(row?.status))return false;if(row.validFrom&&new Date(row.validFrom)>now)return false;if(row.validUntil&&new Date(row.validUntil)<now)return false;return true;}
function orgView(org){return{id:org.id,tenantId:org.tenantId,type:org.type,displayName:org.displayName,fullName:org.fullName||org.displayName,abbreviation:org.abbreviation||null,parentId:org.parentId||null};}
function addWorkspace(map,org,role,detail){if(!org||org.type!=="SCHOOL"||!role)return;const current=map.get(org.id)||{organization:orgView(org),roles:new Set(),access:[]};current.roles.add(role);const signature=JSON.stringify(detail);if(!current.access.some(item=>JSON.stringify(item)===signature))current.access.push(detail);map.set(org.id,current);}function addOrganization(map,org,detail){if(!org)return;const current=map.get(org.id)||{organization:orgView(org),access:[]};const signature=JSON.stringify(detail);if(!current.access.some(item=>JSON.stringify(item)===signature))current.access.push(detail);map.set(org.id,current);}function roleKey(assignment){return assignment?.role?.key||null;}
// Finance is a functional role and must survive inheritance through an org.
// Other organization types keep their existing operational role semantics.
function inheritedGroupRole(role){if(role===ROLE_KEYS.FINANCE)return ROLE_KEYS.FINANCE;if(role===ROLE_KEYS.TENANT_ADMIN)return ROLE_KEYS.TENANT_ADMIN;return ROLE_KEYS.GROUP_STAFF;}
function inheritedOperatorRole(role){return role===ROLE_KEYS.FINANCE?ROLE_KEYS.FINANCE:ROLE_KEYS.BUS_OPERATOR;}
function inheritedPartnerRole(role){return role===ROLE_KEYS.FINANCE?ROLE_KEYS.FINANCE:ROLE_KEYS.SERVICE_PARTNER;}
export async function resolveEffectiveAccessV2(prisma,identity,{now=new Date()}={}){if(!prisma)throw new Error("Canonical control-plane Prisma client is required");const legacyUserId=Number(identity?.id),email=String(identity?.email||"").trim();const user=await prisma.appUser.findFirst({where:{OR:[...(Number.isInteger(legacyUserId)&&legacyUserId>0?[{legacyUserId}]:[]),...(email?[{email}]:[])]},include:{memberships:{include:{organization:true}},roleAssignments:{include:{role:true,organization:true,tenant:true}}}});
if(!user||!activeStatus(user.status))return{source:"canonical-v2",user:user?{id:String(identity?.id||""),appUserId:user.id,email:user.email,displayName:user.displayName}:null,tenantId:null,roles:[],permissions:[],organizations:[],workspaces:[],portfolio:{enabled:false,schoolCount:0}};
const memberships=(user.memberships||[]).filter(activeMembership),membershipOrgIds=new Set(memberships.map(row=>row.organizationId)),assignments=(user.roleAssignments||[]).filter(row=>row.isActive&&roleKey(row)),platformAssignments=assignments.filter(row=>row.scopeType==="PLATFORM"),tenantAssignments=assignments.filter(row=>row.scopeType==="TENANT"&&row.tenantId),organizationAssignments=assignments.filter(row=>row.scopeType==="ORGANIZATION"&&row.organizationId),tenantIdsFromMemberships=new Set(memberships.map(row=>row.organization?.tenantId).filter(Boolean));const validOrganizationAssignments=organizationAssignments.filter(assignment=>membershipOrgIds.has(assignment.organizationId)||(assignment.organization?.type==="SCHOOL"&&tenantIdsFromMemberships.has(assignment.organization.tenantId)));const tenantIds=new Set([...tenantIdsFromMemberships,...tenantAssignments.map(row=>row.tenantId)]),tenantId=tenantIds.size===1?[...tenantIds][0]:null,workspaceMap=new Map(),organizationMap=new Map();
for(const assignment of validOrganizationAssignments){addOrganization(organizationMap,assignment.organization,{kind:"direct",role:roleKey(assignment),viaOrganizationId:assignment.organizationId});if(assignment.organization?.type==="SCHOOL")addWorkspace(workspaceMap,assignment.organization,roleKey(assignment),{kind:"direct",role:roleKey(assignment),viaOrganizationId:assignment.organizationId});}
for(const assignment of validOrganizationAssignments.filter(row=>row.organization?.type==="SCHOOL_GROUP")){const relationships=await prisma.organizationRelationship.findMany({where:{toOrganizationId:assignment.organizationId,type:"BELONGS_TO_GROUP"},include:{fromOrganization:true}});for(const relationship of relationships.filter(row=>activeRelationship(row,now))){const inheritedRole=inheritedGroupRole(roleKey(assignment)),detail={kind:"relationship",role:inheritedRole,viaOrganizationId:assignment.organizationId,viaRelationship:"BELONGS_TO_GROUP"};addWorkspace(workspaceMap,relationship.fromOrganization,inheritedRole,detail);addOrganization(organizationMap,relationship.fromOrganization,detail);}}
for(const assignment of tenantAssignments){const schools=await prisma.organization.findMany({where:{tenantId:assignment.tenantId,type:"SCHOOL",status:"active"}});for(const school of schools){const detail={kind:"tenant",role:roleKey(assignment),viaTenantId:assignment.tenantId};addWorkspace(workspaceMap,school,roleKey(assignment),detail);addOrganization(organizationMap,school,detail);}}
for(const assignment of validOrganizationAssignments.filter(row=>row.organization?.type==="BUS_OPERATOR")){const relationships=await prisma.organizationRelationship.findMany({where:{toOrganizationId:assignment.organizationId,type:"TRANSPORT_PROVIDER"},include:{fromOrganization:true}});for(const relationship of relationships.filter(row=>activeRelationship(row,now))){const inheritedRole=inheritedOperatorRole(roleKey(assignment)),detail={kind:"relationship",role:inheritedRole,viaOrganizationId:assignment.organizationId,viaRelationship:"TRANSPORT_PROVIDER"};addWorkspace(workspaceMap,relationship.fromOrganization,inheritedRole,detail);addOrganization(organizationMap,relationship.fromOrganization,detail);}}
for(const assignment of validOrganizationAssignments.filter(row=>row.organization?.type==="SERVICE_PARTNER")){const relationships=await prisma.organizationRelationship.findMany({where:{toOrganizationId:assignment.organizationId,type:"TRIP_MANAGER"},include:{fromOrganization:true}});for(const relationship of relationships.filter(row=>activeRelationship(row,now))){const inheritedRole=inheritedPartnerRole(roleKey(assignment)),detail={kind:"relationship",role:inheritedRole,viaOrganizationId:assignment.organizationId,viaRelationship:"TRIP_MANAGER"};addWorkspace(workspaceMap,relationship.fromOrganization,inheritedRole,detail);addOrganization(organizationMap,relationship.fromOrganization,detail);}}
const workspaces=[...workspaceMap.values()].sort((a,b)=>a.organization.displayName.localeCompare(b.organization.displayName)).map(({organization,roles,access})=>{const workspaceRoles=[...roles].sort();return{schoolId:organization.id,displayName:organization.displayName,fullName:organization.fullName,abbreviation:organization.abbreviation,roles:workspaceRoles,permissions:permissionsForRoles(workspaceRoles),access};});const directRoles=assignments.map(roleKey).filter(Boolean),roles=[...new Set(directRoles)].sort(),organizations=[...organizationMap.values()].sort((a,b)=>a.organization.displayName.localeCompare(b.organization.displayName)).map(({organization,access})=>({...organization,access}));return{source:"canonical-v2",user:{id:String(identity?.id||""),appUserId:user.id,email:user.email,displayName:user.displayName},tenantId,roles,permissions:permissionsForRoles([...roles,...platformAssignments.map(roleKey)]),organizations,workspaces,portfolio:{enabled:workspaces.length>0,schoolCount:workspaces.length}};}
