import React,{useEffect,useMemo,useState}from"react";
import{confirmWorkspaceTrip,createWorkspaceBusAssignment,deleteWorkspaceBusAssignment,getWorkspaceBusAssignments,submitWorkspaceQuotation,updateWorkspaceBusAssignment}from"../services/tripService";
import{useWorkspace}from"../context/WorkspaceContext";import{toast}from"react-toastify";import ModalWrapper from"./ModalWrapper";

const AssignBusForm=({trip,onClose,onSubmit})=>{
  const{selectedWorkspace}=useWorkspace(),schoolId=selectedWorkspace?.schoolId;
  const preparing=trip?.status==="Accepted",approved=trip?.status==="Approved",operational=approved||trip?.status==="Confirmed";
  const[busType,setBusType]=useState("Internal Yellow Bus"),[busSeats,setBusSeats]=useState((Number(trip?.students)||0)+(Number(trip?.staff)||0)||"");
  const[price,setPrice]=useState(""),[currency,setCurrency]=useState("AED"),[driverName,setDriverName]=useState(""),[driverPhone,setDriverPhone]=useState("");
  const[assignments,setAssignments]=useState([]),[editingId,setEditingId]=useState(null),[submitting,setSubmitting]=useState(false),[loading,setLoading]=useState(true);
  const load=async()=>{if(!schoolId)return;try{setLoading(true);setAssignments(await getWorkspaceBusAssignments(schoolId,trip.id));}catch(e){toast.error(e?.response?.data?.message||"Unable to load bus assignments.");}finally{setLoading(false);}};
  useEffect(()=>{setAssignments([]);setEditingId(null);load();},[schoolId,trip.id]);
  const totals=useMemo(()=>assignments.reduce((out,a)=>{const c=a.currency||"AED";out[c]=(out[c]||0)+(Number(a.price)||0);return out;},{}),[assignments]);
  const incompleteDrivers=useMemo(()=>assignments.filter(a=>String(a.status||"").toLowerCase()!=="cancelled"&&(!String(a.driverName||"").trim()||!String(a.driverPhone||"").trim())),[assignments]);
  const reset=()=>{setBusType("Internal Yellow Bus");setBusSeats((Number(trip?.students)||0)+(Number(trip?.staff)||0)||"");setPrice("");setCurrency("AED");setDriverName("");setDriverPhone("");setEditingId(null);};
  const edit=a=>{setEditingId(a.id);setBusType(a.busType||"Internal Yellow Bus");setBusSeats(a.seatCapacity??"");setPrice(a.price??"");setCurrency(a.currency||"AED");setDriverName(a.driverName||"");setDriverPhone(a.driverPhone||"");};
  const saveBus=async()=>{if(!preparing)return toast.error("Quotation terms can only be prepared while the trip is Accepted.");if(!schoolId||busSeats==="")return toast.error("Please enter number of seats.");if(price==="")return toast.error("Please enter the quoted price for this bus.");const payload={busType,seatCapacity:Number(busSeats),price,currency,driverName:driverName||null,driverPhone:driverPhone||null};try{if(editingId)await updateWorkspaceBusAssignment(schoolId,trip.id,editingId,payload);else await createWorkspaceBusAssignment(schoolId,trip.id,payload);await load();reset();toast.success(editingId?"Quotation line updated.":"Bus added to quotation.");}catch(e){toast.error(e?.response?.data?.message||"Failed to save quotation line.");}};
  const saveDriver=async()=>{if(!approved||!editingId)return;if(!driverName.trim()||!driverPhone.trim())return toast.error("Driver name and phone are both required before final confirmation.");try{setSubmitting(true);await updateWorkspaceBusAssignment(schoolId,trip.id,editingId,{driverName:driverName.trim(),driverPhone:driverPhone.trim()});await load();reset();toast.success("Driver details saved.");}catch(e){toast.error(e?.response?.data?.message||"Failed to save driver details.");}finally{setSubmitting(false);}};
  const remove=async a=>{if(!preparing)return;try{await deleteWorkspaceBusAssignment(schoolId,trip.id,a.id);await load();if(editingId===a.id)reset();}catch(e){toast.error(e?.response?.data?.message||"Failed to remove bus assignment.");}};
  const submitQuote=async()=>{if(!assignments.length)return toast.error("Please add at least one bus before submitting the quotation.");try{setSubmitting(true);const quotation=await submitWorkspaceQuotation(schoolId,trip.id);toast.success("Quotation submitted for school approval.");onSubmit?.({...trip,status:"Quotation Submitted",quotation});onClose();}catch(e){toast.error(e?.response?.data?.message||"Failed to submit quotation.");}finally{setSubmitting(false);}};
  const confirmTrip=async()=>{if(!approved)return;if(!assignments.length)return toast.error("At least one bus is required before final confirmation.");if(incompleteDrivers.length)return toast.error(`Complete driver name and phone for ${incompleteDrivers.length} bus${incompleteDrivers.length===1?"":"es"} before confirming.`);if(!window.confirm("Confirm this trip? This means the approved buses have been operationally booked and driver details are complete."))return;try{setSubmitting(true);const updated=await confirmWorkspaceTrip(schoolId,trip.id);toast.success("Trip confirmed.");onSubmit?.(updated?.trip||{...trip,status:"Confirmed"});onClose();}catch(e){toast.error(e?.response?.data?.message||"Failed to confirm trip.");}finally{setSubmitting(false);}};
  const title=preparing?"Prepare Quotation":approved?"Finalize Bus Details":trip?.status==="Confirmed"?"Confirmed Bus Details":"Bus Details";
  return <ModalWrapper title={title} onClose={onClose} maxWidth="max-w-2xl"><div className="space-y-4">
    {preparing&&<p className="text-sm text-gray-600">Add each required bus and its quoted price. Driver details can be added now or after the school approves the quotation.</p>}
    {approved&&<p className="text-sm text-gray-600">The school has approved this quotation. Add any missing driver details for each bus, then confirm the trip once your operational booking is complete.</p>}
    {trip?.status==="Confirmed"&&<p className="rounded border border-green-200 bg-green-50 p-3 text-sm text-green-800">This trip is confirmed. Quotation terms remain locked.</p>}
    {preparing&&<div className="grid grid-cols-1 md:grid-cols-2 gap-3"><div><label className="block text-sm font-medium">Bus Type</label><select value={busType} onChange={e=>setBusType(e.target.value)} className="w-full p-2 border rounded"><option>Internal Yellow Bus</option><option>External Yellow Bus</option><option>White Bus</option></select></div><div><label className="block text-sm font-medium">Number of Seats</label><input type="number" min="0" value={busSeats} onChange={e=>setBusSeats(e.target.value)} className="w-full p-2 border rounded"/></div><div><label className="block text-sm font-medium">Quoted Price</label><div className="flex gap-2"><input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)} className="min-w-0 flex-1 p-2 border rounded"/><input maxLength="3" value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())} className="w-20 p-2 border rounded"/></div></div><div/><div><label className="block text-sm font-medium">Driver Name <span className="font-normal text-gray-400">(optional now)</span></label><input value={driverName} onChange={e=>setDriverName(e.target.value)} className="w-full p-2 border rounded"/></div><div><label className="block text-sm font-medium">Driver Phone <span className="font-normal text-gray-400">(optional now)</span></label><input value={driverPhone} onChange={e=>setDriverPhone(e.target.value)} className="w-full p-2 border rounded"/></div></div>}
    {preparing&&<button type="button" onClick={saveBus} disabled={submitting} className="w-full bg-green-600 text-white px-4 py-2 rounded disabled:opacity-60">{editingId?"Update Quotation Line":"Add Bus to Quotation"}</button>}
    {approved&&editingId&&<div className="rounded border bg-gray-50 p-3 space-y-3"><p className="text-sm font-medium">Bus driver details</p><p className="text-xs text-gray-500">Quotation terms are locked. Only operational details are being updated.</p><div className="grid grid-cols-1 md:grid-cols-2 gap-3"><div><label className="block text-sm font-medium">Driver Name</label><input value={driverName} onChange={e=>setDriverName(e.target.value)} className="w-full p-2 border rounded bg-white"/></div><div><label className="block text-sm font-medium">Driver Phone</label><input value={driverPhone} onChange={e=>setDriverPhone(e.target.value)} className="w-full p-2 border rounded bg-white"/></div></div><div className="flex gap-2"><button type="button" onClick={saveDriver} disabled={submitting} className="rounded bg-blue-600 px-4 py-2 text-sm text-white disabled:opacity-60">Save Driver Details</button><button type="button" onClick={reset} disabled={submitting} className="rounded border bg-white px-4 py-2 text-sm">Cancel</button></div></div>}
    {loading?<p className="text-sm text-gray-500">Loading assignments…</p>:assignments.length>0&&<div className="bg-gray-50 p-3 rounded"><div className="flex justify-between mb-2 gap-3"><p className="font-medium">{preparing?"Quotation":"Assigned Buses"}</p><div className="text-right">{Object.entries(totals).map(([c,v])=><p key={c} className="font-semibold">Total: {c} {v.toFixed(2)}</p>)}</div></div>{assignments.map((a,i)=>{const missing=!String(a.driverName||"").trim()||!String(a.driverPhone||"").trim();return <div key={a.id} className="border-b py-3 last:border-b-0"><div className="flex justify-between items-start gap-3"><div><p className="text-sm">#{i+1}: {a.busType||"Bus"} · {a.seatCapacity??"—"} seats · {a.currency||"AED"} {a.price??"—"}</p><p className={`mt-1 text-xs ${missing&&approved?"text-amber-700":"text-gray-500"}`}>{missing?"Driver details not complete":`${a.driverName} · ${a.driverPhone}`}</p></div>{preparing?<div className="flex gap-2 shrink-0"><button type="button" onClick={()=>edit(a)} className="text-blue-600 text-sm">Edit</button><button type="button" onClick={()=>remove(a)} className="text-red-600 text-sm">Remove</button></div>:approved?<button type="button" onClick={()=>edit(a)} className="shrink-0 text-blue-600 text-sm">{missing?"Add Driver":"Edit Driver"}</button>:null}</div></div>})}</div>}
    {!preparing&&!operational&&<p className="text-sm text-amber-700 bg-amber-50 border border-amber-200 rounded p-3">Submitted quotation terms are locked while school approval is pending.</p>}
    {approved&&incompleteDrivers.length>0&&<p className="rounded border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">Driver name and phone are required for every active bus before the Bus Operator can confirm the trip.</p>}
    <div className="flex gap-2">{preparing&&<button type="button" onClick={submitQuote} disabled={submitting||loading} className="flex-1 bg-blue-600 text-white px-4 py-2 rounded disabled:opacity-60">{submitting?"Submitting...":"Submit Quotation"}</button>}{approved&&<button type="button" onClick={confirmTrip} disabled={submitting||loading||!assignments.length||incompleteDrivers.length>0} className="flex-1 bg-blue-600 text-white px-4 py-2 rounded disabled:opacity-50">{submitting?"Confirming...":"Confirm Trip"}</button>}<button type="button" onClick={onClose} className="flex-1 bg-gray-300 px-4 py-2 rounded">Close</button></div>
  </div></ModalWrapper>;
};
export default AssignBusForm;
