import React,{useEffect,useMemo,useState}from"react";
import{createWorkspaceBusAssignment,deleteWorkspaceBusAssignment,getWorkspaceBusAssignments,submitWorkspaceQuotation,updateWorkspaceBusAssignment}from"../services/tripService";
import{useAuth}from"../context/AuthContext";import{toast}from"react-toastify";import ModalWrapper from"./ModalWrapper";

const AssignBusForm=({trip,onClose,onSubmit})=>{
  const{activeWorkspace}=useAuth(),schoolId=activeWorkspace?.schoolId;
  const[busType,setBusType]=useState("Internal Yellow Bus"),[busSeats,setBusSeats]=useState((Number(trip?.students)||0)+(Number(trip?.staff)||0)||"");
  const[price,setPrice]=useState(""),[currency,setCurrency]=useState("AED"),[driverName,setDriverName]=useState(""),[driverPhone,setDriverPhone]=useState("");
  const[assignments,setAssignments]=useState([]),[editingId,setEditingId]=useState(null),[submitting,setSubmitting]=useState(false),[loading,setLoading]=useState(true);
  const locked=trip?.status!=="Accepted";
  const load=async()=>{if(!schoolId)return;try{setLoading(true);setAssignments(await getWorkspaceBusAssignments(schoolId,trip.id));}catch(e){toast.error(e?.response?.data?.message||"Unable to load bus assignments.");}finally{setLoading(false);}};
  useEffect(()=>{load();},[schoolId,trip.id]);
  const total=useMemo(()=>assignments.reduce((sum,a)=>sum+(Number(a.price)||0),0),[assignments]);
  const reset=()=>{setBusType("Internal Yellow Bus");setBusSeats((Number(trip?.students)||0)+(Number(trip?.staff)||0)||"");setPrice("");setCurrency("AED");setDriverName("");setDriverPhone("");setEditingId(null);};
  const saveBus=async()=>{if(locked)return toast.error("Quotation terms can only be prepared while the trip is Accepted.");if(!schoolId||!busSeats)return toast.error("Please enter number of seats.");if(price==="")return toast.error("Please enter the quoted price for this bus.");const payload={busType,seatCapacity:Number(busSeats),price,currency,driverName:driverName||null,driverPhone:driverPhone||null};try{if(editingId)await updateWorkspaceBusAssignment(schoolId,trip.id,editingId,payload);else await createWorkspaceBusAssignment(schoolId,trip.id,payload);await load();reset();toast.success(editingId?"Quotation line updated.":"Bus added to quotation.");}catch(e){toast.error(e?.response?.data?.message||"Failed to save quotation line.");}};
  const edit=a=>{setEditingId(a.id);setBusType(a.busType||"Internal Yellow Bus");setBusSeats(a.seatCapacity??"");setPrice(a.price??"");setCurrency(a.currency||"AED");setDriverName(a.driverName||"");setDriverPhone(a.driverPhone||"");};
  const remove=async a=>{if(locked)return;try{await deleteWorkspaceBusAssignment(schoolId,trip.id,a.id);await load();if(editingId===a.id)reset();}catch(e){toast.error(e?.response?.data?.message||"Failed to remove bus assignment.");}};
  const submitQuote=async()=>{if(!assignments.length)return toast.error("Please add at least one bus before submitting the quotation.");try{setSubmitting(true);const quotation=await submitWorkspaceQuotation(schoolId,trip.id);toast.success("Quotation submitted for school approval.");onSubmit?.({...trip,status:"Quotation Submitted",quotation});onClose();}catch(e){toast.error(e?.response?.data?.message||"Failed to submit quotation.");}finally{setSubmitting(false);}};
  return <ModalWrapper title="Prepare Quotation" onClose={onClose} maxWidth="max-w-2xl"><div className="space-y-4">
    <p className="text-sm text-gray-600">Add each required bus and its quoted price. Driver details can be added now or after the school approves the quotation.</p>
    <div className="grid grid-cols-1 md:grid-cols-2 gap-3"><div><label className="block text-sm font-medium">Bus Type</label><select disabled={locked} value={busType} onChange={e=>setBusType(e.target.value)} className="w-full p-2 border rounded disabled:bg-gray-100"><option>Internal Yellow Bus</option><option>External Yellow Bus</option><option>White Bus</option></select></div><div><label className="block text-sm font-medium">Number of Seats</label><input disabled={locked} type="number" min="0" value={busSeats} onChange={e=>setBusSeats(e.target.value)} className="w-full p-2 border rounded disabled:bg-gray-100"/></div><div><label className="block text-sm font-medium">Quoted Price</label><div className="flex gap-2"><input disabled={locked} type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)} className="min-w-0 flex-1 p-2 border rounded disabled:bg-gray-100"/><input disabled={locked} maxLength="3" value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())} className="w-20 p-2 border rounded disabled:bg-gray-100"/></div></div><div/><div><label className="block text-sm font-medium">Driver Name <span className="font-normal text-gray-400">(optional now)</span></label><input disabled={locked} value={driverName} onChange={e=>setDriverName(e.target.value)} className="w-full p-2 border rounded disabled:bg-gray-100"/></div><div><label className="block text-sm font-medium">Driver Phone <span className="font-normal text-gray-400">(optional now)</span></label><input disabled={locked} value={driverPhone} onChange={e=>setDriverPhone(e.target.value)} className="w-full p-2 border rounded disabled:bg-gray-100"/></div></div>
    {!locked&&<button type="button" onClick={saveBus} className="w-full bg-green-600 text-white px-4 py-2 rounded">{editingId?"Update Quotation Line":"Add Bus to Quotation"}</button>}
    {loading?<p className="text-sm text-gray-500">Loading assignments…</p>:assignments.length>0&&<div className="bg-gray-50 p-3 rounded"><div className="flex justify-between mb-2"><p className="font-medium">Quotation</p><p className="font-semibold">Total: {currency} {total.toFixed(2)}</p></div>{assignments.map((a,i)=><div key={a.id} className="flex justify-between items-center border-b py-2 gap-3"><span>#{i+1}: {a.busType||"Bus"} · {a.seatCapacity??"—"} seats · {a.currency||"AED"} {a.price??"—"}</span>{!locked&&<div className="flex gap-2 shrink-0"><button type="button" onClick={()=>edit(a)} className="text-blue-600 text-sm">Edit</button><button type="button" onClick={()=>remove(a)} className="text-red-600 text-sm">Remove</button></div>}</div>)}</div>}
    {locked&&<p className="text-sm text-amber-700 bg-amber-50 border border-amber-200 rounded p-3">This quotation is no longer in preparation. Submitted commercial terms are locked to protect the school approval.</p>}
    <div className="flex gap-2">{!locked&&<button type="button" onClick={submitQuote} disabled={submitting||loading} className="flex-1 bg-blue-600 text-white px-4 py-2 rounded disabled:opacity-60">{submitting?"Submitting...":"Submit Quotation"}</button>}<button type="button" onClick={onClose} className="flex-1 bg-gray-300 px-4 py-2 rounded">Close</button></div>
  </div></ModalWrapper>;
};
export default AssignBusForm;
