import React,{useEffect,useRef,useState}from"react";import{updateWorkspaceTrip}from"../services/tripService";import{useAuth}from"../context/AuthContext";import{toast}from"react-toastify";import"react-toastify/dist/ReactToastify.css";
const TYPES=["Academic Trip","Boarding House Trip","Day Trip","Sports Trip"];
const toDateInput=v=>{if(!v)return"";if(typeof v==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(v))return v;const d=new Date(v);if(Number.isNaN(d.getTime()))return"";return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;};
const parseTime=s=>{if(!s)return{hour:"08",minute:"00",ampm:"AM"};const[time,ampm]=String(s).split(" "),[hour,minute]=(time||"08:00").split(":");return{hour:(hour||"08").padStart(2,"0"),minute:(minute||"00").padStart(2,"0"),ampm:(ampm||"AM").toUpperCase()};};
export default function EditTripForm({trip,onClose,onUpdated}){const{activeWorkspace}=useAuth(),schoolId=activeWorkspace?.schoolId,dep=parseTime(trip.departureTime),ret=parseTime(trip.returnTime),knownType=TYPES.includes(trip.tripType);const[formData,setFormData]=useState({tripType:knownType?trip.tripType:"Other",customType:knownType?"":trip.tripType||"",origin:trip.origin||"School",destination:trip.destination||"",date:toDateInput(trip.date),departureHour:dep.hour,departureMinute:dep.minute,departureAmPm:dep.ampm,returnDate:toDateInput(trip.returnDate)||toDateInput(trip.date),returnHour:ret.hour,returnMinute:ret.minute,returnAmPm:ret.ampm,students:trip.students??"",staff:trip.staff??"",notes:trip.notes||"",boosterSeatsRequested:!!trip.boosterSeatsRequested,boosterSeatCount:trip.boosterSeatCount||""}),[timeError,setTimeError]=useState(""),[submitting,setSubmitting]=useState(false);const prevDateRef=useRef(formData.date);
useEffect(()=>{setFormData(p=>({...p,returnHour:p.departureHour,returnMinute:p.departureMinute,returnAmPm:p.departureAmPm}));},[formData.departureHour,formData.departureMinute,formData.departureAmPm]);useEffect(()=>{setFormData(p=>!p.returnDate||p.returnDate===prevDateRef.current?{...p,returnDate:p.date}:p);prevDateRef.current=formData.date;},[formData.date]);
const change=e=>{const{name,value,type,checked}=e.target;setFormData(p=>name==="boosterSeatsRequested"?{...p,boosterSeatsRequested:checked,boosterSeatCount:checked?p.boosterSeatCount||"":""}:{...p,[name]:type==="checkbox"?checked:value});};
const validate=()=>{const a=new Date(`${formData.date} ${formData.departureHour}:${formData.departureMinute} ${formData.departureAmPm}`),b=new Date(`${formData.returnDate} ${formData.returnHour}:${formData.returnMinute} ${formData.returnAmPm}`);if(b<=a){setTimeError("Return time must be later than departure time.");return false;}setTimeError("");if(formData.boosterSeatsRequested&&Number(formData.boosterSeatCount)<=0){toast.error("Please enter a valid number of booster seats.");return false;}return true;};
const save=async e=>{e.preventDefault();if(!schoolId){toast.error("Select a school workspace first.");return;}if(!validate())return;const payload={tripType:formData.tripType==="Other"?formData.customType.trim():formData.tripType,origin:formData.origin.trim()||null,destination:formData.destination.trim(),date:formData.date,departureTime:`${formData.departureHour}:${formData.departureMinute} ${formData.departureAmPm}`,returnDate:formData.returnDate,returnTime:`${formData.returnHour}:${formData.returnMinute} ${formData.returnAmPm}`,students:Number(formData.students),staff:formData.staff===""?null:Number(formData.staff),notes:formData.notes,boosterSeatsRequested:formData.boosterSeatsRequested,boosterSeatCount:formData.boosterSeatsRequested?Number(formData.boosterSeatCount):0};try{setSubmitting(true);const updated=await updateWorkspaceTrip(schoolId,trip.id,payload);toast.success("Trip updated successfully.");onUpdated?.(updated);onClose?.();}catch(error){console.error(error);toast.error(error?.response?.data?.message||"Failed to update trip.");}finally{setSubmitting(false);}};
const cancel=async()=>{if(!schoolId)return;const nextStatus=trip.status==="Pending"?"Canceled":["Accepted","Confirmed"].includes(trip.status)?"Cancel Requested":null;if(!nextStatus){toast.error("This trip cannot be cancelled from its current status.");return;}if(!window.confirm(nextStatus==="Cancel Requested"?"Send a cancellation request for this trip?":"Cancel this trip?"))return;try{setSubmitting(true);const updated=await updateWorkspaceTrip(schoolId,trip.id,{status:nextStatus,cancelRequest:nextStatus==="Cancel Requested"});toast.success(nextStatus==="Cancel Requested"?"Cancellation requested.":"Trip cancelled.");onUpdated?.(updated);onClose?.();}catch(error){console.error(error);toast.error(error?.response?.data?.message||"Failed to update cancellation status.");}finally{setSubmitting(false);}};
const hours=Array.from({length:12},(_,i)=>String(i+1).padStart(2,"0")),minutes=["00","15","30","45"];
return <div className="fixed inset-0 bg-black bg-opacity-50 flex justify-center items-center z-50 p-2"><div className="bg-white p-4 rounded-lg shadow-xl w-full max-w-xl max-h-screen overflow-y-auto relative"><button onClick={onClose} className="absolute top-2 right-2 text-gray-500 hover:text-black text-xl">&times;</button><h3 className="text-xl font-semibold mb-1">Edit Trip</h3><p className="text-xs text-gray-500 mb-4">{activeWorkspace?.displayName}</p><form onSubmit={save} className="space-y-4">
<div><label className="block text-sm font-medium">Trip Type *</label><select name="tripType" value={formData.tripType} onChange={change} className="w-full p-2 border rounded" required>{[...TYPES,"Other"].map(t=><option key={t}>{t}</option>)}</select>{formData.tripType==="Other"&&<input name="customType" value={formData.customType} onChange={change} placeholder="Enter custom trip type" className="w-full p-2 border rounded mt-2" required/>}</div>
<div className="grid grid-cols-1 sm:grid-cols-2 gap-2"><div><label className="block text-sm font-medium">Origin</label><input name="origin" value={formData.origin} onChange={change} className="w-full p-2 border rounded"/></div><div><label className="block text-sm font-medium">Destination *</label><input name="destination" value={formData.destination} onChange={change} className="w-full p-2 border rounded" required/></div></div>
<div className="grid grid-cols-1 sm:grid-cols-2 gap-2"><div><label className="block text-sm font-medium">Departure Date *</label><input type="date" name="date" value={formData.date} onChange={change} className="w-full p-2 border rounded" required/></div><div><label className="block text-sm font-medium">Departure Time *</label><div className="flex gap-1"><select name="departureHour" value={formData.departureHour} onChange={change} className="w-1/3 p-2 border rounded">{hours.map(x=><option key={x}>{x}</option>)}</select><select name="departureMinute" value={formData.departureMinute} onChange={change} className="w-1/3 p-2 border rounded">{minutes.map(x=><option key={x}>{x}</option>)}</select><select name="departureAmPm" value={formData.departureAmPm} onChange={change} className="w-1/3 p-2 border rounded"><option>AM</option><option>PM</option></select></div></div></div>
<div className="grid grid-cols-1 sm:grid-cols-2 gap-2"><div><label className="block text-sm font-medium">Return Date *</label><input type="date" name="returnDate" value={formData.returnDate} onChange={change} className="w-full p-2 border rounded" required/></div><div><label className="block text-sm font-medium">Return Time *</label><div className="flex gap-1"><select name="returnHour" value={formData.returnHour} onChange={change} className="w-1/3 p-2 border rounded">{hours.map(x=><option key={x}>{x}</option>)}</select><select name="returnMinute" value={formData.returnMinute} onChange={change} className="w-1/3 p-2 border rounded">{minutes.map(x=><option key={x}>{x}</option>)}</select><select name="returnAmPm" value={formData.returnAmPm} onChange={change} className="w-1/3 p-2 border rounded"><option>AM</option><option>PM</option></select></div>{timeError&&<p className="text-red-500 text-sm mt-1">{timeError}</p>}</div></div>
<div className="grid grid-cols-1 sm:grid-cols-2 gap-2"><div><label className="block text-sm font-medium">Number of Students *</label><input type="number" min="0" name="students" value={formData.students} onChange={change} className="w-full p-2 border rounded" required/></div><div><label className="block text-sm font-medium">Number of Staff</label><input type="number" min="0" name="staff" value={formData.staff} onChange={change} className="w-full p-2 border rounded"/></div></div>
<label className="flex items-center gap-2 text-sm"><input type="checkbox" name="boosterSeatsRequested" checked={formData.boosterSeatsRequested} onChange={change}/>Request Booster Seats</label>{formData.boosterSeatsRequested&&<input type="number" min="1" name="boosterSeatCount" value={formData.boosterSeatCount} onChange={change} placeholder="Number of Booster Seats" className="w-full p-2 border rounded"/>}<div><label className="block text-sm font-medium">Additional Notes</label><textarea name="notes" value={formData.notes} onChange={change} className="w-full p-2 border rounded"/></div>
<div className="flex gap-2"><button type="submit" disabled={submitting} className="bg-blue-600 text-white px-4 py-2 rounded flex-1 disabled:opacity-50">{submitting?"Saving...":"Save Changes"}</button><button type="button" onClick={onClose} className="bg-gray-300 px-4 py-2 rounded flex-1">Ignore Changes</button></div>{["Pending","Accepted","Confirmed"].includes(trip.status)&&<button type="button" disabled={submitting} onClick={cancel} className="bg-red-600 text-white w-full px-4 py-3 rounded disabled:opacity-50">{trip.status==="Pending"?"Cancel Trip":"Request Cancel"}</button>}</form></div></div>;
}
