import React,{useEffect,useMemo,useState}from"react";
import{getWorkspaceQuotation}from"../services/tripService";
import{useWorkspace}from"../context/WorkspaceContext";

const changeRequest=q=>(q?.approvalRequests||[]).find(a=>a.status==="changes_requested"&&a.decisionNote);
const totalText=q=>{const totals={};for(const line of q?.lines||[]){const currency=line.currency||"AED";totals[currency]=(totals[currency]||0)+(Number(line.price)||0);}return Object.entries(totals).map(([c,v])=>`${c} ${v.toFixed(2)}`).join(" · ")||"—";};
const dateText=value=>{if(!value)return"";const d=new Date(value);return Number.isNaN(d.getTime())?"":d.toLocaleString();};

export default function QuotationHistory({trip}){const{selectedWorkspace}=useWorkspace(),schoolId=selectedWorkspace?.schoolId,[quotation,setQuotation]=useState(null),[loading,setLoading]=useState(false);useEffect(()=>{let live=true;(async()=>{if(!schoolId||!trip?.id)return;try{setLoading(true);const q=await getWorkspaceQuotation(schoolId,trip.id);if(live)setQuotation(q);}catch{if(live)setQuotation(null);}finally{if(live)setLoading(false);}})();return()=>{live=false};},[schoolId,trip?.id,trip?.status]);const versions=useMemo(()=>quotation?[quotation,...(quotation.history||[])]:[],[quotation]);const latestRequest=changeRequest(quotation);
if(loading||!quotation)return null;
return <section className="rounded-lg border bg-white p-4 space-y-3">{trip?.status==="Accepted"&&latestRequest&&<div className="rounded-lg border border-amber-300 bg-amber-50 p-4"><p className="font-semibold text-amber-950">Changes requested</p><p className="mt-1 text-sm text-amber-900 whitespace-pre-wrap">{latestRequest.decisionNote}</p><p className="mt-2 text-xs text-amber-700">Revise the bus details or pricing, then prepare and submit the quotation again. A new quotation version will be created.</p></div>}<details><summary className="cursor-pointer text-sm font-semibold text-gray-800">Quotation history ({versions.length} version{versions.length===1?"":"s"})</summary><div className="mt-3 space-y-2">{versions.map((q,index)=>{const request=changeRequest(q);return <div key={q.id} className="rounded border bg-gray-50 p-3 text-sm"><div className="flex flex-wrap items-center justify-between gap-2"><div><span className="font-semibold">Version {q.version}</span><span className="ml-2 text-gray-500">{index===0?"Latest":"Previous"} · {q.status}</span></div><span className="font-medium">{totalText(q)}</span></div><div className="mt-1 text-xs text-gray-500">Submitted {dateText(q.submittedAt)}</div>{request&&<div className="mt-2 rounded border border-amber-200 bg-amber-50 px-3 py-2 text-amber-900"><span className="font-medium">Changes requested:</span> {request.decisionNote}</div>}</div>})}</div></details></section>;
}
