// client/src/components/TripForm.jsx
import React,{useState,useEffect}from"react";import{createWorkspaceTrip}from"../services/tripService";import{useAuth}from"../context/AuthContext";import{toast}from"react-toastify";import"react-toastify/dist/ReactToastify.css";
const TripForm=({onSuccess,onClose})=>{const{activeWorkspace}=useAuth();const[formData,setFormData]=useState({tripType:"Academic Trip",customType:"",origin:"School",destination:"",date:"",departureHour:"08",departureMinute:"00",departureAmPm:"AM",returnDate:"",returnHour:"08",returnMinute:"00",returnAmPm:"AM",students:"",staff:"",notes:"",boosterSeatsRequested:false,boosterSeatCount:""});const[submitting,setSubmitting]=useState(false),[timeError,setTimeError]=useState("");
useEffect(()=>{setFormData(p=>({...p,returnHour:p.departureHour,returnMinute:p.departureMinute,returnAmPm:p.departureAmPm}));},[formData.departureHour,formData.departureMinute,formData.departureAmPm]);
const handleChange=e=>{const{name,value,type,checked}=e.target;setFormData(p=>({...p,[name]:type==="checkbox"?checked:value}));};
const validateTimes=()=>{const dep=new Date(`${formData.date} ${formData.departureHour}:${formData.departureMinute} ${formData.departureAmPm}`),ret=new Date(`${formData.returnDate||formData.date} ${formData.returnHour}:${formData.returnMinute} ${formData.returnAmPm}`);if(ret<=dep){setTimeError("Return time must be later than departure time.");return false;}setTimeError("");return true;};
const handleSubmit=async e=>{e.preventDefault();if(!activeWorkspace?.schoolId){toast.error("No school workspace is selected.");return;}if(!validateTimes())return;setSubmitting(true);try{const payload={tripType:formData.tripType==="Other"?formData.customType:formData.tripType,origin:formData.origin||null,destination:formData.destination,date:formData.date,departureTime:`${formData.departureHour}:${formData.departureMinute} ${formData.departureAmPm}`,returnDate:formData.returnDate||formData.date,returnTime:`${formData.returnHour}:${formData.returnMinute} ${formData.returnAmPm}`,students:Number(formData.students),staff:formData.staff===""?null:Number(formData.staff),notes:formData.notes,boosterSeatsRequested:formData.boosterSeatsRequested,boosterSeatCount:formData.boosterSeatsRequested?Number(formData.boosterSeatCount):0};await createWorkspaceTrip(activeWorkspace.schoolId,payload);toast.success("Trip submitted successfully!");onSuccess?.();}catch(error){console.error("Failed to submit trip:",error);toast.error(error?.response?.data?.message||"Submission failed. Please try again.");}finally{setSubmitting(false);}};
const hours=Array.from({length:12},(_,i)=>(i+1).toString().padStart(2,"0")),mins=["00","15","30","45"],types=["Academic Trip","Boarding House Trip","Day Trip","Sports Trip","Other"];
return <form onSubmit={handleSubmit} className="space-y-4 p-4"><h3 className="text-xl font-semibold">Request a New Trip</h3><p className="text-sm text-gray-500">{activeWorkspace?.displayName}</p>
<div><label className="block text-sm font-medium">Trip Type *</label><select name="tripType" value={formData.tripType} onChange={handleChange} className="w-full p-2 border rounded" required>{types.map(x=><option key={x}>{x}</option>)}</select>{formData.tripType==="Other"&&<input name="customType" placeholder="Enter custom trip type" value={formData.customType} onChange={handleChange} className="w-full p-2 border rounded mt-2" required/>}</div>
<div className="grid grid-cols-1 sm:grid-cols-2 gap-2"><div><label className="block text-sm font-medium">Origin</label><input name="origin" value={formData.origin} onChange={handleChange} className="w-full p-2 border rounded"/></div><div><label className="block text-sm font-medium">Destination *</label><input name="destination" value={formData.destination} onChange={handleChange} required className="w-full p-2 border rounded"/></div></div>
<div className="flex gap-2"><div className="flex-1"><label className="block text-sm font-medium mb-1">Departure Date *</label><input type="date" name="date" value={formData.date} onChange={handleChange} required className="w-full p-2 border rounded h-10"/></div><div className="flex-1"><label className="block text-sm font-medium mb-1">Departure Time *</label><div className="flex gap-1"><select name="departureHour" value={formData.departureHour} onChange={handleChange} className="w-1/3 p-2 border rounded">{hours.map(x=><option key={x}>{x}</option>)}</select><select name="departureMinute" value={formData.departureMinute} onChange={handleChange} className="w-1/3 p-2 border rounded">{mins.map(x=><option key={x}>{x}</option>)}</select><select name="departureAmPm" value={formData.departureAmPm} onChange={handleChange} className="w-1/3 p-2 border rounded"><option>AM</option><option>PM</option></select></div></div></div>
<div className="flex gap-2"><div className="flex-1"><label className="block text-sm font-medium mb-1">Return Date *</label><input type="date" name="returnDate" value={formData.returnDate||formData.date} onChange={handleChange} required className="w-full p-2 border rounded h-10"/></div><div className="flex-1"><label className="block text-sm font-medium mb-1">Return Time *</label><div className="flex gap-1"><select name="returnHour" value={formData.returnHour} onChange={handleChange} className="w-1/3 p-2 border rounded">{hours.map(x=><option key={x}>{x}</option>)}</select><select name="returnMinute" value={formData.returnMinute} onChange={handleChange} className="w-1/3 p-2 border rounded">{mins.map(x=><option key={x}>{x}</option>)}</select><select name="returnAmPm" value={formData.returnAmPm} onChange={handleChange} className="w-1/3 p-2 border rounded"><option>AM</option><option>PM</option></select></div>{timeError&&<p className="text-red-500 text-sm mt-1">{timeError}</p>}</div></div>
<div className="grid grid-cols-2 gap-2"><div><label className="block text-sm font-medium">Number of Students *</label><input type="number" min="0" name="students" value={formData.students} onChange={handleChange} required className="w-full p-2 border rounded"/></div><div><label className="block text-sm font-medium">Number of Staff</label><input type="number" min="0" name="staff" value={formData.staff} onChange={handleChange} className="w-full p-2 border rounded"/></div></div>
<label className="flex items-center space-x-2"><input type="checkbox" name="boosterSeatsRequested" checked={formData.boosterSeatsRequested} onChange={handleChange}/><span className="text-sm">Request Booster Seats</span></label>{formData.boosterSeatsRequested&&<input type="number" min="0" name="boosterSeatCount" placeholder="Number of Booster Seats" value={formData.boosterSeatCount} onChange={handleChange} className="w-full p-2 border rounded"/>}
<div><label className="block text-sm font-medium">Additional Notes</label><textarea name="notes" value={formData.notes} onChange={handleChange} className="w-full p-2 border rounded"/></div><div className="flex gap-2"><button type="submit" disabled={submitting} className="bg-blue-600 text-white px-4 py-2 rounded flex-1">{submitting?"Submitting...":"Submit Trip"}</button><button type="button" onClick={onClose} className="bg-gray-300 px-4 py-2 rounded flex-1">Cancel</button></div></form>};export default TripForm;
