// client/src/components/TripDetails.jsx
import React from "react";
import StatusBadge from "./StatusBadge";
import { useAuth } from "../context/AuthContext";
import ActionsCell from "./actions/ActionsCell";
import ConfirmActionPopup from "./ConfirmActionPopup";
import AssignBusForm from "./AssignBusForm";
import EditTripForm from "./EditTripForm";
import PassengersPanel from "./trips/PassengersPanel";
import useTripActions from "../hooks/useTripActions";
import { getWorkspaceBusAssignments } from "../services/tripService";
import { RxPerson } from "react-icons/rx";
import ModalWrapper from "./ModalWrapper";

function EmailPopover({ email = "-", onClose }) {const ref=React.useRef(null);const[copyState,setCopyState]=React.useState("idle");React.useEffect(()=>{const click=e=>{if(ref.current&&!ref.current.contains(e.target))onClose?.();},key=e=>e.key==="Escape"&&onClose?.();document.addEventListener("mousedown",click);document.addEventListener("keydown",key);return()=>{document.removeEventListener("mousedown",click);document.removeEventListener("keydown",key);};},[onClose]);const copy=async()=>{try{await navigator.clipboard.writeText(email||"");setCopyState("success");setTimeout(()=>setCopyState("idle"),1200);}catch{setCopyState("error");}};return <div ref={ref} className="absolute z-[200] mt-1 right-0 w-64 rounded border bg-white shadow p-3 text-sm"><div className="font-mono break-all">{email||"-"}</div><div className="mt-2 flex justify-end"><button type="button" onClick={copy} className="px-2 py-1 rounded border hover:bg-gray-50">{copyState==="success"?"Copied!":copyState==="error"?"Retry":"Copy"}</button></div></div>}

function TripDetails({trip}){if(!trip)return null;const{activeWorkspace}=useAuth(),permissions=new Set(activeWorkspace?.permissions||[]),schoolId=activeWorkspace?.schoolId,canReadPassengers=permissions.has("passenger.read"),canManagePassengers=permissions.has("passenger.manage"),canReadAssignments=permissions.has("bus_assignment.read");const[currentTrip,setCurrentTrip]=React.useState(trip),[assignments,setAssignments]=React.useState([]),[assignmentsLoading,setAssignmentsLoading]=React.useState(false);React.useEffect(()=>setCurrentTrip(trip),[trip]);
const loadAssignments=React.useCallback(async()=>{if(!schoolId||!trip?.id||!canReadAssignments){setAssignments([]);return;}try{setAssignmentsLoading(true);setAssignments(await getWorkspaceBusAssignments(schoolId,trip.id));}catch(e){console.error("Failed to load bus assignments",e);setAssignments([]);}finally{setAssignmentsLoading(false);}},[schoolId,trip?.id,canReadAssignments]);React.useEffect(()=>{loadAssignments();},[loadAssignments]);
const[,setSink]=React.useState([]),{handleStatusChange,handleSoftDelete}=useTripActions(activeWorkspace,setSink);const[confirmAction,setConfirmAction]=React.useState(null),[assignTrip,setAssignTrip]=React.useState(null),[editTrip,setEditTrip]=React.useState(null),[showPassengersTrip,setShowPassengersTrip]=React.useState(null),[showRequesterEmail,setShowRequesterEmail]=React.useState(false);const patchTrip=updated=>{if(!updated)return;setCurrentTrip(prev=>({...prev,...updated}));try{window.dispatchEvent(new CustomEvent("trip:updated",{detail:{...currentTrip,...updated}}));}catch{}};const canSeePassengersButton=canReadPassengers&&["Accepted","Confirmed","Completed"].includes(currentTrip?.status);const formatDate=s=>{if(!s)return"-";const d=new Date(s);if(Number.isNaN(d.getTime()))return String(s);return`${String(d.getDate()).padStart(2,"0")}-${d.toLocaleString("default",{month:"short"})}-${d.getFullYear()}`;};const requester={name:currentTrip.requesterName||currentTrip.requestedByName||currentTrip.createdByName||currentTrip.ownerName||"—",email:currentTrip.requesterEmail||currentTrip.requestedByEmail||currentTrip.createdByEmail||currentTrip.ownerEmail||""};const students=currentTrip.students??"—",staff=Number.isFinite(Number(currentTrip.staff))?Number(currentTrip.staff):null,total=(Number.isFinite(Number(students))?Number(students):0)+(staff??0),origin=currentTrip.origin||"School",destination=currentTrip.destination||"—";
return <div className="space-y-4"><div><h2 className="text-xl font-bold mb-2">Trip Summary</h2><div className="grid grid-cols-1 sm:grid-cols-2 gap-4 bg-gray-50 p-4 rounded border [&_strong]:font-medium"><div><strong>Trip Type:</strong> {currentTrip.tripType}</div><div className="relative"><strong>Requested by:</strong> <button className="text-blue-600 hover:underline font-medium" onClick={()=>setShowRequesterEmail(s=>!s)}>{requester.name}</button>{showRequesterEmail&&<EmailPopover email={requester.email} onClose={()=>setShowRequesterEmail(false)}/>}</div><div><strong>Origin:</strong> {origin}</div><div><strong>Destination:</strong> {destination}</div><div><strong>Departure:</strong> {formatDate(currentTrip.date)} at {currentTrip.departureTime||"-"}</div><div><strong>Return:</strong> {formatDate(currentTrip.returnDate)} at {currentTrip.returnTime||"-"}</div><div><strong>Students:</strong> {students}<span className="ml-4"><strong>Staff:</strong> {staff??"not set"}</span></div><div><strong>Passengers (Total):</strong> {total||"—"}</div>{currentTrip.notes&&<div className="sm:col-span-2"><strong>Notes:</strong> {currentTrip.notes}</div>}<div className="sm:col-span-2 flex items-center"><strong className="mr-1">Status:</strong><StatusBadge status={currentTrip.status}/></div></div></div>
<div className="pt-1 flex flex-col gap-2 sm:flex-row sm:gap-4"><ActionsCell trip={currentTrip} hideView onStatusChange={async(t,s)=>patchTrip(await handleStatusChange(t,s))} onAssignBus={setAssignTrip} onConfirmAction={(t,label,nextStatus)=>setConfirmAction({trip:t,label,nextStatus})} onEdit={setEditTrip} onSoftDelete={handleSoftDelete}/>{canSeePassengersButton&&<button onClick={()=>setShowPassengersTrip(currentTrip)} className="flex items-center px-2 py-1 border rounded text-sm font-semibold text-gray-700"><RxPerson className="mr-1"/>{canManagePassengers?"Manage Passengers":"View Passengers"}</button>}</div>
{canReadAssignments&&<><hr className="my-2 border-gray-300"/><div><h3 className="text-lg font-semibold mb-2">Assigned Buses</h3>{assignmentsLoading?<p className="text-sm text-gray-500">Loading bus assignments…</p>:assignments.length===0?<p className="text-sm text-gray-500">No buses assigned.</p>:<div className="space-y-3">{assignments.map((a,index)=><div key={a.id} className="bg-white border rounded p-4 shadow-sm"><p className="font-medium mb-1">Bus #{index+1}</p><div className="grid grid-cols-2 gap-3 text-sm"><div><strong>Type:</strong> {a.busType||"-"}</div><div><strong>Seats:</strong> {a.seatCapacity??"-"}</div>{a.price!=null&&<div><strong>Price:</strong> {a.currency||"AED"} {a.price}</div>}{a.driverName&&<div><strong>Driver Name:</strong> {a.driverName}</div>}{a.driverPhone&&<div><strong>Driver Phone:</strong> {a.driverPhone}</div>}<div><strong>Status:</strong> {a.status||"Assigned"}</div></div></div>)}</div>}</div></>}
{assignTrip&&<div className="fixed inset-0 bg-black/40 flex justify-center items-center z-50 p-4"><AssignBusForm trip={assignTrip} onClose={()=>setAssignTrip(null)} onSubmit={async updated=>{setAssignTrip(null);patchTrip(updated);await loadAssignments();}}/></div>}{confirmAction&&<ConfirmActionPopup title={`${confirmAction.label} Trip`} description={`Are you sure you want to ${confirmAction.label.toLowerCase()} this trip?`} onConfirm={async()=>{const c=confirmAction;setConfirmAction(null);patchTrip(await handleStatusChange(c.trip,c.nextStatus));}} onClose={()=>setConfirmAction(null)}/>} {editTrip&&<div className="fixed inset-0 bg-black/40 flex justify-center items-center z-50 p-4"><EditTripForm trip={editTrip} onClose={()=>setEditTrip(null)} onUpdated={u=>{setEditTrip(null);if(u)patchTrip(u);}}/></div>}{showPassengersTrip&&<ModalWrapper onClose={()=>setShowPassengersTrip(null)}><PassengersPanel trip={showPassengersTrip} readOnly={!canManagePassengers}/></ModalWrapper>}</div>}
export default TripDetails;
