import React,{useState}from"react";
import{FiCalendar,FiList,FiSearch}from"react-icons/fi";
import TripFilters from"../components/TripFilters";
import dayjs from"dayjs";
import{useFilteredTrips}from"../hooks/useFilteredTrips";
import{Surface,SectionHeader}from"../components/ui/Surface";
import SegmentedControl from"../components/ui/SegmentedControl";

const TripsLayout=({title="Trips",trips=[],calendarComponent:CalendarViewComponent,tableComponent:TableViewComponent})=>{const[view,setView]=useState("table");const{filteredTrips,search,setSearch,statusFilter,setStatusFilter,monthFilter,setMonthFilter,bookingTypeFilter,setBookingTypeFilter,dateSortOrder,setDateSortOrder,resetFilters}=useFilteredTrips(trips);const uniqueMonths=Array.from(new Set((trips||[]).map(trip=>trip.departureDate||trip.date||trip.returnDate).filter(Boolean).map(value=>dayjs(value).format("MMMM YYYY")))).sort((a,b)=>dayjs(b,"MMMM YYYY").valueOf()-dayjs(a,"MMMM YYYY").valueOf());const statusOptions=["Pending","Accepted","Quotation Submitted","Approved","Confirmed","Completed","Canceled","Rejected"];const controls=<div className="flex flex-wrap items-center gap-2"><div className="relative min-w-[220px] flex-1 sm:flex-none"><FiSearch className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search trips" className="h-9 w-full rounded-lg border border-slate-200 bg-white pl-9 pr-3 text-sm text-slate-700 outline-none transition focus:border-slate-400 focus:ring-2 focus:ring-slate-100 sm:w-[250px]"/></div>{CalendarViewComponent&&<SegmentedControl value={view} onChange={setView} options={[{value:"table",label:"Table",icon:FiList},{value:"calendar",label:"Calendar",icon:FiCalendar}]}/>}</div>;const typeOptions=[{value:"",label:"All trips"},{value:"single",label:"Single"},{value:"recurring",label:"Recurring"},{value:"modified",label:"Modified occurrences"}];return <Surface padded={false} className="overflow-hidden"><SectionHeader title={<span className="flex items-center gap-2">{title}<span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs font-semibold text-slate-500">{filteredTrips.length}</span></span>} description="Search, filter and switch between operational table and calendar views." actions={controls}/><div className="border-b border-slate-100 px-5 py-3"><div className="mb-3 overflow-x-auto"><SegmentedControl value={bookingTypeFilter} onChange={setBookingTypeFilter} options={typeOptions}/></div><TripFilters search={search} setSearch={setSearch} statusFilter={statusFilter} setStatusFilter={setStatusFilter} statusOptions={statusOptions} monthFilter={monthFilter} setMonthFilter={setMonthFilter} monthOptions={uniqueMonths} onReset={resetFilters} filteredData={filteredTrips}/></div><div className="relative min-h-[620px] w-full bg-white">{view==="calendar"&&CalendarViewComponent?<CalendarViewComponent trips={filteredTrips}/>:<TableViewComponent trips={filteredTrips} dateSortOrder={dateSortOrder} setDateSortOrder={setDateSortOrder}/>}</div></Surface>};
export default TripsLayout;
